/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geopanels;

import Clases.ClaseCliente;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jalex
 */
public class Clientes extends javax.swing.JPanel {

    /**
     * Creates new form Clientes
     */
    ClaseCliente cli = new ClaseCliente();
    public static ResultSet retorno;    
    
    
    public Clientes() {
        initComponents();
        txtIdCliente.setVisible(false);
        txtIdMun.setVisible(false);
        txtIdDep.setVisible(false);
        Llenar_Dep();
        Llenar_Tabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnRefrescar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTel = new javax.swing.JFormattedTextField();
        cmbDep = new javax.swing.JComboBox();
        txtCorreo = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDui = new javax.swing.JFormattedTextField();
        cmbMun = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        txtIdCliente = new javax.swing.JTextField();
        txtIdMun = new javax.swing.JTextField();
        txtIdDep = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(42, 51, 56));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(149, 162, 166));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/icons8-administración-30.png"))); // NOI18N
        jLabel2.setText("Clientes");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel2.setIconTextGap(20);

        jPanel7.setBackground(new java.awt.Color(42, 51, 56));

        btnAgregar.setBackground(new java.awt.Color(27, 35, 41));
        btnAgregar.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(149, 162, 166));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Añadir.png"))); // NOI18N
        btnAgregar.setText("Añadir Elemento");
        btnAgregar.setBorderPainted(false);
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setOpaque(true);
        btnAgregar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Añadir Hover.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnRefrescar.setBackground(new java.awt.Color(27, 35, 41));
        btnRefrescar.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnRefrescar.setForeground(new java.awt.Color(149, 162, 166));
        btnRefrescar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Actualizar.png"))); // NOI18N
        btnRefrescar.setText("Actualizar Lista");
        btnRefrescar.setBorderPainted(false);
        btnRefrescar.setContentAreaFilled(false);
        btnRefrescar.setOpaque(true);
        btnRefrescar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Actualizar Hover.png"))); // NOI18N
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(27, 35, 41));
        btnEditar.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(149, 162, 166));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Editar.png"))); // NOI18N
        btnEditar.setText("Editar Elemento");
        btnEditar.setBorderPainted(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setOpaque(true);
        btnEditar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Editar Hover.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(btnRefrescar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRefrescar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Tabla.setBackground(new java.awt.Color(27, 35, 41));
        Tabla.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        Tabla.setForeground(new java.awt.Color(149, 162, 166));
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Correlativo", "Nombre", "Apellido", "Correo", "Telefono", "Dui", "Direccion", "Municipio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla.setGridColor(new java.awt.Color(27, 35, 41));
        Tabla.setOpaque(false);
        Tabla.setSelectionBackground(new java.awt.Color(149, 162, 166));
        Tabla.setSelectionForeground(new java.awt.Color(42, 51, 56));
        Tabla.getTableHeader().setReorderingAllowed(false);
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TablaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(149, 162, 166));
        jLabel4.setText("Nombre : ");

        lblCorreo.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(149, 162, 166));
        lblCorreo.setText("Correo : ");

        txtNombre.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(27, 35, 41)));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(149, 162, 166));
        jLabel8.setText("Teléfono : ");

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(149, 162, 166));
        jLabel9.setText("Apellido : ");

        btnBuscar.setBackground(new java.awt.Color(27, 35, 41));
        btnBuscar.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(149, 162, 166));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setOpaque(true);
        btnBuscar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Buscar Hover.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(149, 162, 166));
        jLabel10.setText("DUI :");

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(149, 162, 166));
        jLabel7.setText("Dirección : ");

        txtDireccion.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        txtDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(27, 35, 41)));
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(149, 162, 166));
        jLabel11.setText("Departamento :");

        txtTel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(27, 35, 41)));
        try {
            txtTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cmbDep.setBackground(new java.awt.Color(27, 35, 41));
        cmbDep.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "..." }));
        cmbDep.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cmbDep.setOpaque(false);
        cmbDep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbDepMouseClicked(evt);
            }
        });
        cmbDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDepActionPerformed(evt);
            }
        });

        txtCorreo.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        txtCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(27, 35, 41)));
        txtCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoFocusLost(evt);
            }
        });
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoKeyTyped(evt);
            }
        });

        txtApellido.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        txtApellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(27, 35, 41)));

        txtDui.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(27, 35, 41)));
        try {
            txtDui.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cmbMun.setBackground(new java.awt.Color(27, 35, 41));
        cmbMun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));
        cmbMun.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cmbMun.setOpaque(false);
        cmbMun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMunActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(149, 162, 166));
        jLabel15.setText("Municipios :");

        btnLimpiar.setBackground(new java.awt.Color(42, 51, 56));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(149, 162, 166));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Toalla.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setToolTipText("Limpiar Campos");
        btnLimpiar.setBorderPainted(false);
        btnLimpiar.setContentAreaFilled(false);
        btnLimpiar.setOpaque(true);
        btnLimpiar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Toalla Hover.png"))); // NOI18N
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        txtIdCliente.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        txtIdCliente.setForeground(new java.awt.Color(149, 162, 166));
        txtIdCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(27, 35, 41)));

        txtIdMun.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        txtIdMun.setForeground(new java.awt.Color(149, 162, 166));
        txtIdMun.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(27, 35, 41)));

        txtIdDep.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        txtIdDep.setForeground(new java.awt.Color(149, 162, 166));
        txtIdDep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(27, 35, 41)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(cmbDep, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtDui, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel15))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbMun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTel, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                    .addComponent(txtNombre))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(lblCorreo))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApellido)
                                    .addComponent(txtCorreo))))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdMun, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdDep, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiar)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtIdMun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtIdDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLimpiar))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblCorreo)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtDui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cmbMun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(btnBuscar)
                        .addGap(3, 3, 3)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel15))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        add(jPanel4, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    //Tablas
    
    public void Llenar_Dep(){
        cmbDep.setModel(cli.Depto());
        btnEditar.setEnabled(false);
    }
    public void Llenar_Tabla(){
        DefaultTableModel inv = (DefaultTableModel) Tabla.getModel();
        inv.setRowCount(0);
        retorno = cli.Mostrar_Clientes();
        try
        {
            while(retorno.next())
            {
                Vector v = new Vector();
                v.add(retorno.getString(1));
                v.add(retorno.getString(2));
                v.add(retorno.getString(3));
                v.add(retorno.getString(4));
                v.add(retorno.getString(5));
                v.add(retorno.getString(6));
                v.add(retorno.getString(7));
                v.add(retorno.getString(8));
                inv.addRow(v);
                Tabla.setModel(inv);
            }
        }
        catch(SQLException e)
        {
            System.out.println(e.toString());
        }  
    }
    public void Llenar_Busqueda(){
        DefaultTableModel inv = (DefaultTableModel) Tabla.getModel();
        inv.setRowCount(0);
        retorno = cli.Buscar_Cliente();
        try
        {
            while(retorno.next())
            {
                Vector v = new Vector();
                v.add(retorno.getString(1));
                v.add(retorno.getString(2));
                v.add(retorno.getString(3));
                v.add(retorno.getString(4));
                v.add(retorno.getString(5));
                v.add(retorno.getString(6));
                v.add(retorno.getString(7));
                v.add(retorno.getString(8));
                inv.addRow(v);
                Tabla.setModel(inv);
            }
        }
        catch(SQLException e)
        {
            System.out.println(e.toString());
        }  
    }
    public void PasarDatosFila(){
        //Obtenemos los datos
        int filaseleccionada = Tabla.getSelectedRow();
        String identificador = (String)Tabla.getValueAt(filaseleccionada, 0);
        String nombre = (String)Tabla.getValueAt(filaseleccionada, 1);
        String apellido = (String)Tabla.getValueAt (filaseleccionada, 2);
        String numero = (String)Tabla.getValueAt (filaseleccionada,4);
        String correo = (String)Tabla.getValueAt (filaseleccionada,3);
        String dui = (String)Tabla.getValueAt (filaseleccionada, 5);
        String direccion = (String)Tabla.getValueAt (filaseleccionada, 6);
        String municipio = (String)Tabla.getValueAt (filaseleccionada, 7);
        //Volcamos los datos de la tabla en los jTextFields.
        txtIdCliente.setText(identificador);
        txtNombre.setText(nombre);
        txtApellido.setText(apellido);
        txtTel.setText(numero);
        txtCorreo.setText(correo);
        txtDui.setText(dui);
        txtDireccion.setText(direccion);
        
        int dp;
        cli.setMunicipio(municipio);        
        retorno = cli.Obtener_DeptoId();
        try{
                        while(retorno.next())
                        {
                            
                            dp = retorno.getInt(1);
                            //JOptionPane.showMessageDialog(this, "No se pudo obtener el id perteneciente al municipio" + dp);
                            //dp =dp -1;
                            cmbDep.setSelectedIndex(dp);
                            cli.setDepId(dp/*1*/);
                            cmbMun.setModel(cli.Munc());
                            cmbMun.setSelectedItem(municipio);
                        }
                    }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, "No se pudo obtener el id perteneciente al municipio" + e);
            }
    }
    
    //Validacion
    
    public boolean campocorreo (String correo){
        Pattern pat = null;
        Matcher mat = null;
        pat = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"+ "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        mat = pat.matcher(correo);
        return mat.find();
    }
    
    //Cruds
    
    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void cmbDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDepActionPerformed
        cli.setDepartamento((String) cmbDep.getSelectedItem());
        
        retorno = cli.Obtener_DeptoIdby();
        try{
                while(retorno.next()){
                cli.setDepId(retorno.getInt(1));
                cmbMun.setModel(cli.Munc()); 
                //JOptionPane.showMessageDialog(this, "No se pudo obtener el id perteneciente al Departamento" + retorno.getInt(1));
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, "No se pudo obtener el id perteneciente al Departamento" + e);
        }    
    }//GEN-LAST:event_cmbDepActionPerformed

    private void TablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMousePressed
        // TODO add your handling code here:        
    }//GEN-LAST:event_TablaMousePressed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        if (txtIdMun.getText().isEmpty() ||txtNombre.getText().isEmpty() || txtApellido.getText().isEmpty() || txtTel.getText().isEmpty() || txtCorreo.getText().isEmpty() || txtDui.getText().isEmpty() || txtDireccion.getText().isEmpty() || "Seleccione".equals((String)cmbMun.getSelectedItem()) || !campocorreo(txtCorreo.getText()) ) {
            JOptionPane.showMessageDialog(this, "Completa todos los campos o verifica los datos ingresados");
        }
        else {
            
                    cli.setNombre(txtNombre.getText());
                    cli.setApellido(txtApellido.getText());
                    cli.setNumero(txtTel.getText());
                    cli.setCorreo(txtCorreo.getText());
                    cli.setDUI(txtDui.getText());
                    cli.setDireccion(txtDireccion.getText());
                    cli.setMunId(Integer.parseInt(txtIdMun.getText()));
                    
                try {
                        if (cli.Agregar_Cliente()) {
                            JOptionPane.showMessageDialog(this, "Error al guardar datos");
                            Llenar_Tabla();
                        }
                        else{
                            JOptionPane.showMessageDialog(this, "Datos guardados");
                            Llenar_Tabla();
                        }
                    } catch (HeadlessException ex) {
                        Logger.getLogger(Carrito.class.getName()).log(Level.SEVERE, null, ex);
                    }    
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        if (txtIdCliente.getText().isEmpty() || txtIdMun.getText().isEmpty() || txtNombre.getText().isEmpty() ||txtApellido.getText().isEmpty() || txtTel.getText().isEmpty() || txtCorreo.getText().isEmpty() || txtDui.getText().isEmpty() || txtDireccion.getText().isEmpty() || "Seleccione".equals((String)cmbMun.getSelectedItem()) || !campocorreo(txtCorreo.getText())) {
            JOptionPane.showMessageDialog(this, "Completa todos los campos o verifica los datos ingresados");
        }
        else {
            cli.setClienteId(Integer.parseInt(txtIdCliente.getText()));
            cli.setNombre(txtNombre.getText());
            cli.setApellido(txtApellido.getText());
            cli.setNumero(txtTel.getText());
            cli.setCorreo(txtCorreo.getText());
            cli.setDUI(txtDui.getText());
            cli.setDireccion(txtDireccion.getText());
            cli.setMunId(Integer.parseInt(txtIdMun.getText()));
            
            try {
                if (cli.Editar_Cliente()) {
                    JOptionPane.showMessageDialog(this, "Datos Editados");
                    Llenar_Tabla();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Error al editar datos");
                    Llenar_Tabla();
                }
            } catch (HeadlessException ex) {
                Logger.getLogger(Carrito.class.getName()).log(Level.SEVERE, null, ex);
            }                      
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionKeyTyped

    private void txtCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyTyped
        // TODO add your handling code here:
        if(!campocorreo(txtCorreo.getText())){
            lblCorreo.setForeground(new java.awt.Color(250,43,43));
        }
        else if(!campocorreo(txtCorreo.getText())){
            lblCorreo.setForeground(new java.awt.Color(149,162,166));
        }
    }//GEN-LAST:event_txtCorreoKeyTyped

    private void txtCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusLost
        // TODO add your handling code here:
        if(!campocorreo(txtCorreo.getText())){
            JOptionPane.showMessageDialog(null, "¡Verifica que el correo este bien escrito!", "CARACTERES INVALIDOS", JOptionPane.WARNING_MESSAGE);
            txtCorreo.requestFocus();
        }
    }//GEN-LAST:event_txtCorreoFocusLost

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
        PasarDatosFila();
        btnAgregar.setEnabled(false);
        btnEditar.setEnabled(true);
    }//GEN-LAST:event_TablaMouseClicked

    private void cmbDepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbDepMouseClicked
        // TODO add your handling code here:
            
    }//GEN-LAST:event_cmbDepMouseClicked

    private void cmbMunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMunActionPerformed
        // TODO add your handling code here:
        cli.setMunicipio((String)cmbMun.getSelectedItem());
        retorno = cli.Obtener_MunId();
            try{
                while(retorno.next()){
                    txtIdMun.setText(retorno.getString(1));  
                }
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(this, "No se pudo obtener el id perteneciente al municipio" + e);
            }            
    }//GEN-LAST:event_cmbMunActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
    txtApellido.setText("");
    txtCorreo.setText("");
    txtDireccion.setText("");
    txtDui.setText("");
    txtIdCliente.setText("");
    txtIdDep.setText("");
    txtIdMun.setText("");
    txtNombre.setText("");
    txtTel.setText("");
    cmbDep.setSelectedItem("San Salvador");
    Llenar_Tabla();
    btnAgregar.setEnabled(true);
    btnEditar.setEnabled(false);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        // TODO add your handling code here:
        Llenar_Tabla();
    }//GEN-LAST:event_btnRefrescarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if (txtIdMun.getText().isEmpty() && txtNombre.getText().isEmpty() && txtApellido.getText().isEmpty() && txtTel.getText().isEmpty() && txtCorreo.getText().isEmpty() && txtDui.getText().isEmpty() && txtDireccion.getText().isEmpty() && "Seleccione".equals((String)cmbMun.getSelectedItem()) && !campocorreo(txtCorreo.getText()) ) {
            JOptionPane.showMessageDialog(this, "Completa todos los campos o verifica los datos ingresados");
        }
        else {
            
                    cli.setNombre(txtNombre.getText());
                    cli.setApellido(txtApellido.getText());
                    cli.setNumero(txtTel.getText());
                    cli.setCorreo(txtCorreo.getText());
                    cli.setDUI(txtDui.getText());
                    cli.setDireccion(txtDireccion.getText());
                    cli.setMunicipio((String)cmbMun.getSelectedItem());
                    cli.setDepartamento((String) cmbDep.getSelectedItem());
                  
                    Llenar_Busqueda();
                    
               
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JComboBox cmbDep;
    private javax.swing.JComboBox<String> cmbMun;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JFormattedTextField txtDui;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdDep;
    private javax.swing.JTextField txtIdMun;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JFormattedTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
