/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geopanels;
import Clases.ClaseCombo_Compra;
import Clases.ClaseCompra;
import Clases.Conexion;

import geopanels.FiltroProveedor;
import java.net.URLDecoder;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author jalex
 */
public class Compra extends javax.swing.JPanel {

    /**
     * Creates new form Compra
     */
            
        String Valor1, Valor2 = "";//
        
    static ResultSet result;
    
    public Compra() {
        initComponents();
        cargarValores();
        Date objDate = new Date(); 
        String strDateFormat = "dd-MM-yyyy-";         
        SimpleDateFormat objSDF = new SimpleDateFormat(strDateFormat);
        txtFecha.setText(objSDF.format(objDate));
        txtId.setVisible(false);
        txtIdCarrito.setVisible(false);
        
        ClaseCombo_Compra h = new ClaseCombo_Compra();
        h.LlenarComboEstablecimiento(cmbEstablecimiento);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        txtNacimiento = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        P = new javax.swing.JLabel();
        P2 = new javax.swing.JLabel();
        P3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCompra = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        BtnProducto = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        cmbEstablecimiento = new javax.swing.JComboBox<>();
        txtFecha = new javax.swing.JFormattedTextField();
        txtIdCarrito = new javax.swing.JTextField();
        txtCarrito = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        txtDescripcion = new javax.swing.JTextField();

        try {
            txtNacimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        setBackground(new java.awt.Color(42, 51, 56));
        setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(42, 51, 56));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(149, 162, 166));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Compra.png"))); // NOI18N
        jLabel2.setText("Compra");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel2.setIconTextGap(20);

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(149, 162, 166));
        jLabel5.setText("Total :");

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(149, 162, 166));
        jLabel8.setText(" Descripción : ");

        P.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        P.setForeground(new java.awt.Color(149, 162, 166));
        P.setText(" Carrito :");

        P2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        P2.setForeground(new java.awt.Color(149, 162, 166));
        P2.setText(" Fecha :");

        P3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        P3.setForeground(new java.awt.Color(149, 162, 166));
        P3.setText("Establecimiento :");

        TablaCompra.setBackground(new java.awt.Color(42, 51, 56));
        TablaCompra.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        TablaCompra.setForeground(new java.awt.Color(149, 162, 166));
        TablaCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Total", "Descripcion", "Fecha", "Carrito", "Nombre Establecimiento"
            }
        ));
        TablaCompra.setGridColor(new java.awt.Color(50, 54, 59));
        TablaCompra.setOpaque(false);
        TablaCompra.setSelectionBackground(new java.awt.Color(149, 162, 166));
        TablaCompra.setSelectionForeground(new java.awt.Color(50, 54, 59));
        TablaCompra.getTableHeader().setReorderingAllowed(false);
        TablaCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaCompraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaCompra);

        jPanel7.setBackground(new java.awt.Color(42, 51, 56));

        btnAgregar.setBackground(new java.awt.Color(27, 35, 41));
        btnAgregar.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(149, 162, 166));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Añadir.png"))); // NOI18N
        btnAgregar.setText("Añadir Elemento");
        btnAgregar.setBorderPainted(false);
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setOpaque(true);
        btnAgregar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Añadir Hover.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(27, 35, 41));
        btnActualizar.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(149, 162, 166));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Actualizar.png"))); // NOI18N
        btnActualizar.setText("Actualizar Lista");
        btnActualizar.setBorderPainted(false);
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.setOpaque(true);
        btnActualizar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Actualizar Hover.png"))); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(27, 35, 41));
        btnEditar.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(149, 162, 166));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Editar.png"))); // NOI18N
        btnEditar.setText("Editar Elemento");
        btnEditar.setBorderPainted(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setOpaque(true);
        btnEditar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Editar Hover.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BtnProducto.setBackground(new java.awt.Color(27, 35, 41));
        BtnProducto.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        BtnProducto.setForeground(new java.awt.Color(149, 162, 166));
        BtnProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Filtro.png"))); // NOI18N
        BtnProducto.setText("Filtar");
        BtnProducto.setBorderPainted(false);
        BtnProducto.setContentAreaFilled(false);
        BtnProducto.setOpaque(true);
        BtnProducto.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Filtro Hover.png"))); // NOI18N
        BtnProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnProductoMouseClicked(evt);
            }
        });
        BtnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProductoActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(42, 51, 56));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(149, 162, 166));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Toalla.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setToolTipText("Limpiar Campos");
        btnLimpiar.setBorderPainted(false);
        btnLimpiar.setContentAreaFilled(false);
        btnLimpiar.setOpaque(true);
        btnLimpiar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Toalla Hover.png"))); // NOI18N
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        txtId.setEditable(false);
        txtId.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        txtId.setForeground(new java.awt.Color(50, 54, 59));
        txtId.setEnabled(false);

        txtCantidad.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCantidad.setEnabled(false);

        txtFecha.setEditable(false);
        try {
            txtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFecha.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtFecha.setEnabled(false);

        txtIdCarrito.setEditable(false);
        txtIdCarrito.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        txtIdCarrito.setForeground(new java.awt.Color(50, 54, 59));
        txtIdCarrito.setEnabled(false);

        txtCarrito.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCarrito.setEnabled(false);
        txtCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarritoActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(27, 35, 41));
        btnBuscar.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(149, 162, 166));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setOpaque(true);
        btnBuscar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Buscar Hover.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtIdCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                                .addGap(2, 2, 2)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(P)
                                    .addComponent(P2)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(txtCarrito)
                                        .addGap(18, 18, 18)
                                        .addComponent(BtnProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDescripcion))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(P3)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCantidad)
                                    .addComponent(cmbEstablecimiento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLimpiar)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtIdCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(P2)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(P3)
                        .addComponent(cmbEstablecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnProducto)
                    .addComponent(P)
                    .addComponent(jLabel5)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        add(jPanel4, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void TablaCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaCompraMouseClicked
        int col = TablaCompra.getSelectedRow();
        txtId.setText(TablaCompra.getModel().getValueAt(col, 0).toString());
        txtCantidad.setText(TablaCompra.getModel().getValueAt(col, 1).toString());
        txtDescripcion.setText(TablaCompra.getModel().getValueAt(col, 2).toString());
        txtFecha.setText(TablaCompra.getModel().getValueAt(col, 3).toString());
        txtCarrito.setText(TablaCompra.getModel().getValueAt(col, 4).toString());

        String NombreEstablecimiento;

        NombreEstablecimiento = TablaCompra.getModel().getValueAt(col, 5).toString();
        ClaseCombo_Compra mostrar = new ClaseCombo_Compra();

        cmbEstablecimiento.setSelectedIndex(mostrar.CargarTipoEstablecimiento(NombreEstablecimiento));
        //

    }//GEN-LAST:event_TablaCompraMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        Valor1 = txtCarrito.getText();

        if (txtCantidad.getText().equals("") || txtDescripcion.getText().equals("") ||
            txtCarrito.getText().equals("") ||
            txtFecha.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debes completar todos los campos necesarios para continuar el proceso con normalidad.", "ADVERTENCIA", JOptionPane.INFORMATION_MESSAGE);
        }else{
            String CMB;//Establecimiento
            CMB = cmbEstablecimiento.getItemAt(cmbEstablecimiento.getSelectedIndex()).getRespuesta();

            ClaseCompra obj = new ClaseCompra();

            obj.setcantidad(Double.parseDouble(txtCantidad.getText()));
            obj.setdescripcion(txtDescripcion.getText());
            obj.setfecha(txtFecha.getText());

            ClaseCombo_Compra mostrar = new ClaseCombo_Compra();

            int valor4 = (mostrar.CargarCarrito(Valor1));

            obj.setid_carrito(valor4);
            obj.setid_establecimiento(Integer.parseInt(CMB));

            if (obj.guardarCompra()) {
                JOptionPane.showMessageDialog(null, "Datos Guardados");
                cargarValores();
                LimpiarCampos();
            }else{
                JOptionPane.showMessageDialog(null, "Error al guardar datos");
            }

        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        Valor1 = txtCarrito.getText();

        if (txtCantidad.getText().equals("") || txtDescripcion.getText().equals("") ||
            txtCarrito.getText().equals("") ||
            txtFecha.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debes completar todos los campos necesarios para continuar el proceso con normalidad.", "ADVERTENCIA", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            String CMB;//Establecimiento.

            CMB = cmbEstablecimiento.getItemAt(cmbEstablecimiento.getSelectedIndex()).getRespuesta();
            ClaseCompra obj = new ClaseCompra();

            obj.setcantidad(Double.parseDouble(txtCantidad.getText()));
            obj.setdescripcion(txtDescripcion.getText());
            obj.setfecha(txtFecha.getText());
            obj.setid_compra(Integer.parseInt(txtId.getText()));

            ClaseCombo_Compra mostrar = new ClaseCombo_Compra();

            int valor4 = (mostrar.CargarCarrito(Valor1));

            obj.setid_carrito(valor4);
            obj.setid_establecimiento(Integer.parseInt(CMB));

            if (obj.actualizarCompra()) {
                JOptionPane.showMessageDialog(null, "Datos actualizados");
                cargarValores();
                LimpiarCampos();
            }else{
                JOptionPane.showMessageDialog(null, "Error al actualizar datos");
            }

        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Busqueda();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void BtnProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnProductoMouseClicked
        FiltroCarritoCompra cm = new FiltroCarritoCompra();
        cm.setVisible(true);

    }//GEN-LAST:event_BtnProductoMouseClicked

    private void BtnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnProductoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        LimpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarritoActionPerformed
    public void Busqueda(){

        String valor = txtCantidad.getText();
        DefaultTableModel modelo = (DefaultTableModel) TablaCompra.getModel();
        modelo.setRowCount(0);

        //Realizando consulta.
      result = Clases.Conexion.Consulta("select * from Compra where cantidad = '"+valor+"'");
        try{

            while(result.next()){

                //Agregando datos a la tabla.
                Vector datos = new Vector();
                datos.add(result.getInt(1));
                datos.add(result.getInt(2));
                datos.add(result.getString(3));
                datos.add(result.getString(4));
                datos.add(result.getInt(5));
                datos.add(result.getInt(6));
                
                modelo.addRow(datos);
                TablaCompra.setModel(modelo);

                //Ocultando la columna 0.
                TablaCompra.getColumnModel().getColumn(0).setMaxWidth(0);
                TablaCompra.getColumnModel().getColumn(0).setMinWidth(0);
                TablaCompra.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
                TablaCompra.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
            }
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
        public void cargarValores() {
     
       DefaultTableModel modelo = (DefaultTableModel) TablaCompra.getModel();
       modelo.setRowCount(0);
       
       result = Clases.Conexion.Consulta("Select c.id_compra, c.total, c.descripcion, c.fecha, f.carrito, e.nombre_establecimiento from Compra c, Producto d, Establecimiento e, Carrito f where  c.id_carrito = f.id_carrito AND c.id_establecimiento = e.id_establecimiento");
       try{
       
           while(result.next()){
             
               Vector valor = new Vector();
                valor.add(result.getInt(1));
                valor.add(result.getInt(2));
                valor.add(result.getString(3));
                valor.add(result.getString(4));
                
                valor.add(result.getString(5));
                valor.add(result.getString(6));
               modelo.addRow(valor);
               TablaCompra.setModel(modelo);
               
               
               TablaCompra.getColumnModel().getColumn(0).setMaxWidth(0);
               TablaCompra.getColumnModel().getColumn(0).setMinWidth(0);
               TablaCompra.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
               TablaCompra.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
           }
       }
       catch(Exception e){
       
           System.out.println(e.getMessage());
       }
          }
        private void LimpiarCampos(){
        txtCantidad.setText(null);
        txtDescripcion.setText(null);
        txtFecha.setText(null);
        txtCarrito.setText("");
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnProducto;
    private javax.swing.JLabel P;
    private javax.swing.JLabel P2;
    private javax.swing.JLabel P3;
    private javax.swing.JTable TablaCompra;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<ClaseCombo_Compra> cmbEstablecimiento;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    public static javax.swing.JTextField txtCantidad;
    public static javax.swing.JTextField txtCarrito;
    public static javax.swing.JTextField txtDescripcion;
    private javax.swing.JFormattedTextField txtFecha;
    private javax.swing.JTextField txtId;
    public static javax.swing.JTextField txtIdCarrito;
    private javax.swing.JFormattedTextField txtNacimiento;
    // End of variables declaration//GEN-END:variables
}
