/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geopanels;
import Clases.ClaseCombo_Contrato;
import Clases.ClaseContrato;
import java.sql.ResultSet;
import geopanels.FiltroCosto;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author jalex
 */
public class Contrato extends javax.swing.JPanel {

    /**
     * Creates new form Contrato
     */
    static ResultSet result;
    String Valor1, Valor2, Valor3 = "";
    public Contrato() {
        initComponents();
         cargarContrato();
        txtID.setVisible(false);
        txtCliente.setEnabled(false);
        txtTipoMan.setEnabled(false);
        txtProduccion.setEnabled(false);
        ClaseCombo_Contrato h = new ClaseCombo_Contrato();
        h.LlenarComboTipoContrato(cbxTipoContrato);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaContrato = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtGarantia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtRend = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        btnFiltroCli = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtTipoMan = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtRecargo = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btnFiltroProd = new javax.swing.JButton();
        btnFiltroMan = new javax.swing.JButton();
        txtMensualidad = new javax.swing.JTextField();
        txtProduccion = new javax.swing.JTextField();
        cbxTipoContrato = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtFechaIn = new javax.swing.JFormattedTextField();
        txtFechaFin = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(42, 51, 56));
        setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(42, 51, 56));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(149, 162, 166));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Firma.png"))); // NOI18N
        jLabel2.setText("Contratos");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel2.setIconTextGap(20);

        TablaContrato.setBackground(new java.awt.Color(27, 35, 41));
        TablaContrato.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        TablaContrato.setForeground(new java.awt.Color(149, 162, 166));
        TablaContrato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Mensualidad", "Garantia", "Fecha inicio", "Fecha fin", "Rendimiento", "Costo", "Produccion", "Recargo", "Title 10", "Nombre cliente", "Tipo contrato", "Codigo"
            }
        ));
        TablaContrato.setGridColor(new java.awt.Color(27, 35, 41));
        TablaContrato.setOpaque(false);
        TablaContrato.setSelectionBackground(new java.awt.Color(149, 162, 166));
        TablaContrato.setSelectionForeground(new java.awt.Color(50, 54, 59));
        TablaContrato.getTableHeader().setReorderingAllowed(false);
        TablaContrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaContratoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaContrato);

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(149, 162, 166));
        jLabel3.setText("Mensualidad : ");

        jButton3.setBackground(new java.awt.Color(27, 35, 41));
        jButton3.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(149, 162, 166));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Buscar.png"))); // NOI18N
        jButton3.setText("Buscar");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setOpaque(true);
        jButton3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Buscar Hover.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(149, 162, 166));
        jLabel10.setText("Recargo : ");

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(149, 162, 166));
        jLabel13.setText("Codigo de contrato :");

        txtCliente.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        txtCliente.setForeground(new java.awt.Color(50, 54, 59));
        txtCliente.setEnabled(false);

        btnFiltroCli.setBackground(new java.awt.Color(27, 35, 41));
        btnFiltroCli.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        btnFiltroCli.setForeground(new java.awt.Color(149, 162, 166));
        btnFiltroCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Filtro.png"))); // NOI18N
        btnFiltroCli.setText("Filtro");
        btnFiltroCli.setBorderPainted(false);
        btnFiltroCli.setContentAreaFilled(false);
        btnFiltroCli.setOpaque(true);
        btnFiltroCli.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Filtro Hover.png"))); // NOI18N
        btnFiltroCli.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnFiltroCliAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnFiltroCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFiltroCliMouseClicked(evt);
            }
        });
        btnFiltroCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroCliActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(149, 162, 166));
        jLabel15.setText("Tipo Mantenimiento");

        txtTipoMan.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("000000.00"))));

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(149, 162, 166));
        jLabel16.setText("Fecha de Inicio : ");

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(149, 162, 166));
        jLabel17.setText("Rendimiento : ");

        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(149, 162, 166));
        jLabel18.setText("Tipo Contrato : ");

        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(149, 162, 166));
        jLabel19.setText("Fecha de Fin : ");

        jPanel7.setBackground(new java.awt.Color(42, 51, 56));

        btnAgregar.setBackground(new java.awt.Color(27, 35, 41));
        btnAgregar.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(149, 162, 166));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Añadir.png"))); // NOI18N
        btnAgregar.setText("Añadir Elemento");
        btnAgregar.setBorderPainted(false);
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setOpaque(true);
        btnAgregar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Añadir Hover.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(27, 35, 41));
        btnActualizar.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(149, 162, 166));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Actualizar.png"))); // NOI18N
        btnActualizar.setText("Actualizar Lista");
        btnActualizar.setBorderPainted(false);
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.setOpaque(true);
        btnActualizar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Actualizar Hover.png"))); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnMostrar.setBackground(new java.awt.Color(27, 35, 41));
        btnMostrar.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnMostrar.setForeground(new java.awt.Color(149, 162, 166));
        btnMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Editar.png"))); // NOI18N
        btnMostrar.setText("Editar Elemento");
        btnMostrar.setBorderPainted(false);
        btnMostrar.setContentAreaFilled(false);
        btnMostrar.setOpaque(true);
        btnMostrar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Editar Hover.png"))); // NOI18N
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        btnLimpiar.setBackground(new java.awt.Color(42, 51, 56));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(149, 162, 166));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Toalla.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setToolTipText("Limpiar Campos");
        btnLimpiar.setBorderPainted(false);
        btnLimpiar.setContentAreaFilled(false);
        btnLimpiar.setOpaque(true);
        btnLimpiar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Toalla Hover.png"))); // NOI18N
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(149, 162, 166));
        jLabel4.setText("Garantia :");

        jLabel20.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(149, 162, 166));
        jLabel20.setText("Produccion :");

        btnFiltroProd.setBackground(new java.awt.Color(27, 35, 41));
        btnFiltroProd.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        btnFiltroProd.setForeground(new java.awt.Color(149, 162, 166));
        btnFiltroProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Filtro.png"))); // NOI18N
        btnFiltroProd.setText("Filtro");
        btnFiltroProd.setBorderPainted(false);
        btnFiltroProd.setContentAreaFilled(false);
        btnFiltroProd.setOpaque(true);
        btnFiltroProd.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Filtro Hover.png"))); // NOI18N
        btnFiltroProd.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnFiltroProdAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnFiltroProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFiltroProdMouseClicked(evt);
            }
        });
        btnFiltroProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroProdActionPerformed(evt);
            }
        });

        btnFiltroMan.setBackground(new java.awt.Color(27, 35, 41));
        btnFiltroMan.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        btnFiltroMan.setForeground(new java.awt.Color(149, 162, 166));
        btnFiltroMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Filtro.png"))); // NOI18N
        btnFiltroMan.setText("Filtro");
        btnFiltroMan.setBorderPainted(false);
        btnFiltroMan.setContentAreaFilled(false);
        btnFiltroMan.setOpaque(true);
        btnFiltroMan.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Filtro Hover.png"))); // NOI18N
        btnFiltroMan.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnFiltroManAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnFiltroMan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFiltroManMouseClicked(evt);
            }
        });
        btnFiltroMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroManActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(149, 162, 166));
        jLabel14.setText("Cliente : ");

        try {
            txtFechaIn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtFechaFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFechaFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaFinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLimpiar))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel14))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnFiltroCli, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtRend, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRecargo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtMensualidad)
                                            .addComponent(txtGarantia, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                                        .addGap(36, 36, 36)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel16)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel18)
                                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(txtProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnFiltroProd, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(cbxTipoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFechaIn, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                            .addComponent(txtFechaFin))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(txtTipoMan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnFiltroMan, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)))))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLimpiar)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTipoMan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(btnFiltroMan, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtMensualidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel16))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtRecargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txtFechaIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFiltroProd, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(cbxTipoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFiltroCli, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel14))
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtRend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(jPanel4, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
   public void cargarContrato(){

        DefaultTableModel modelo = (DefaultTableModel) TablaContrato.getModel();
        modelo.setRowCount(0);

        //Realizando consulta.
        result = Clases.Conexion.Consulta("Select c.id_contrato, c.mensualidad, c.garantia, c.fecha_inicio, c.fecha_fin, c.rendimiento, m.tipo_mantenimiento, o.produccion, c.recargo, n.nombre_cliente, t.tipo_contrato, c.codigo from Contrato c, Cliente n, Tipo_contrato t, Tipo_mantenimiento m, Produccion o where c.id_cliente = n.id_cliente AND c.id_tipo_contrato = t.id_tipo_contrato AND c.costo = m.id_tipo_mantenimiento AND c.produccion = o.id_produccion");

        try{

            while(result.next()){

                //Agregando datos a la tabla.
                Vector datos = new Vector();
                datos.add(result.getInt(1));
                datos.add(result.getInt(2));
                datos.add(result.getString(3));
                datos.add(result.getString(4));
                datos.add(result.getString(5));
                datos.add(result.getString(6));
                datos.add(result.getString(7));
                datos.add(result.getString(8));
                datos.add(result.getInt(9));
                datos.add(result.getString(10));
                datos.add(result.getString(11));
                datos.add(result.getInt(12));
                modelo.addRow(datos);
                TablaContrato.setModel(modelo);

                //Ocultando la columna 0.
                TablaContrato.getColumnModel().getColumn(0).setMaxWidth(0);
                TablaContrato.getColumnModel().getColumn(0).setMinWidth(0);
                TablaContrato.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
                TablaContrato.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
            }
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    private void TablaContratoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaContratoMouseClicked
        int col = TablaContrato.getSelectedRow();
        txtID.setText(TablaContrato.getModel().getValueAt(col, 0).toString());
        txtMensualidad.setText(TablaContrato.getModel().getValueAt(col, 1).toString());
        txtGarantia.setText(TablaContrato.getModel().getValueAt(col, 2).toString());
        txtFechaIn.setText(TablaContrato.getModel().getValueAt(col, 3).toString());
        txtFechaFin.setText(TablaContrato.getModel().getValueAt(col, 4).toString());
        txtRend.setText(TablaContrato.getModel().getValueAt(col, 5).toString());
        txtTipoMan.setText(TablaContrato.getModel().getValueAt(col, 6).toString());
        txtProduccion.setText(TablaContrato.getModel().getValueAt(col, 7).toString());
        txtRecargo.setText(TablaContrato.getModel().getValueAt(col, 8).toString());
        txtCliente.setText(TablaContrato.getModel().getValueAt(col, 9).toString());
        txtCodigo.setText(TablaContrato.getModel().getValueAt(col,11).toString());

        String TipContrato;//Tipo Contrato

        TipContrato = TablaContrato.getModel().getValueAt(col, 10).toString();
        

        ClaseCombo_Contrato mostrar = new ClaseCombo_Contrato();
        cbxTipoContrato.setSelectedIndex(mostrar.CargarTipoContrato(TipContrato));

    }//GEN-LAST:event_TablaContratoMouseClicked
public void LimpiarCampos(){
txtMensualidad.setText(null);
txtGarantia.setText(null);
txtRecargo.setText(null);
txtCodigo.setText(null);
txtCliente.setText(null);
txtRend.setText(null);
txtTipoMan.setText(null);
txtFechaIn.setText(null);
txtFechaFin.setText(null);
txtProduccion.setText(null);

}

public void Consulta(){
        String nombre = (txtRend.getText());
        DefaultTableModel modelo = (DefaultTableModel) TablaContrato.getModel();
        modelo.setRowCount(0);
        //Realizando la consulta.
        result = Clases.Conexion.Consulta("Select * From Contrato where rendimiento = '"+nombre+"'");
        try{
            while(result.next()){
                Vector valor = new Vector();
                //Enviando datos a la tabla.
                valor.add(result.getInt(1));
                valor.add(result.getInt(2));
                valor.add(result.getString(3));
                valor.add(result.getString(4));
                valor.add(result.getString(5));
                valor.add(result.getString(6));
                valor.add(result.getInt(7));
                valor.add(result.getInt(8));
                valor.add(result.getInt(9));
                valor.add(result.getInt(10));
                valor.add(result.getInt(11));
                valor.add(result.getInt(12));
                    
              
                modelo.addRow(valor);
                TablaContrato.setModel(modelo);
                
                //Ocultando la columna 0.
                TablaContrato.getColumnModel().getColumn(0).setMaxWidth(0);
                TablaContrato.getColumnModel().getColumn(0).setMinWidth(0);
                TablaContrato.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
                TablaContrato.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }

    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnFiltroCliAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnFiltroCliAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFiltroCliAncestorAdded

    private void btnFiltroCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiltroCliMouseClicked
        // TODO add your handling code here:
        FiltroCL fc = new FiltroCL();
        fc.setVisible(true);
    }//GEN-LAST:event_btnFiltroCliMouseClicked

    private void btnFiltroCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroCliActionPerformed
     
    }//GEN-LAST:event_btnFiltroCliActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        Valor1 = txtCliente.getText();
        Valor2 = txtTipoMan.getText();
        Valor3 = txtProduccion.getText();

        if (txtMensualidad.getText().equals("") || txtGarantia.getText().equals("") || txtRecargo.getText().equals("") || txtCliente.getText().equals("") ||
            txtRend.getText().equals("") || txtTipoMan.getText().equals("") || txtFechaIn.getText().equals("") || txtFechaFin.getText().equals("") ||
            txtFechaIn.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debes completar todos los campos necesarios para continuar el proceso con normalidad.", "ADVERTENCIA", JOptionPane.INFORMATION_MESSAGE);
        }else{
            String CMB;//MUNICIPIO.

            CMB = cbxTipoContrato.getItemAt(cbxTipoContrato.getSelectedIndex()).getRespuesta();

            ClaseContrato obj = new ClaseContrato();

            obj.setmensualidad(Double.parseDouble(txtMensualidad.getText()));
            obj.setgarantia(txtGarantia.getText());
            obj.setfecha_inicio(txtFechaIn.getText());
            obj.setfecha_fin(txtFechaFin.getText());
            obj.setrendimiento(txtRend.getText());
            obj.setrecargo(Double.parseDouble(txtRecargo.getText()));
            obj.setcodigo(Integer.parseInt(txtCodigo.getText()));

            ClaseCombo_Contrato mostrar = new ClaseCombo_Contrato();

            int costo = (mostrar.CargarCosto(Valor2));
            int produccion = (mostrar.CargarProduccion(Valor3));
            int cliente = (mostrar.CargarCliente(Valor1));

            obj.setcosto(costo);
            obj.setproduccion(produccion);
            obj.setid_cliente(cliente);
            obj.setid_tipo_contrato(Integer.parseInt(CMB));

            if (obj.guardarContrato()) {
                JOptionPane.showMessageDialog(null, "Datos Guardados");
                cargarContrato();
                LimpiarCampos();
            }else{
                JOptionPane.showMessageDialog(null, "Error al guardar datos");
            }
        }

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
         if (txtMensualidad.getText().equals("") || txtGarantia.getText().equals("") || txtRecargo.getText().equals("") || txtCliente.getText().equals("") ||
            txtRend.getText().equals("") || txtTipoMan.getText().equals("") || txtFechaIn.getText().equals("") || txtFechaFin.getText().equals("") ||
            txtFechaIn.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debes completar todos los campos necesarios para continuar el proceso con normalidad.", "ADVERTENCIA", JOptionPane.INFORMATION_MESSAGE);
        }else{
         
         Valor1 = txtCliente.getText();
        Valor2 = txtTipoMan.getText();
        Valor3 = txtProduccion.getText();

        String CMB;//MUNICIPIO.

        CMB = cbxTipoContrato.getItemAt(cbxTipoContrato.getSelectedIndex()).getRespuesta();

        ClaseContrato obj = new ClaseContrato();

        obj.setmensualidad(Double.parseDouble(txtMensualidad.getText()));
        obj.setgarantia(txtGarantia.getText());
        obj.setfecha_inicio(txtFechaIn.getText());
        obj.setfecha_fin(txtFechaFin.getText());
        obj.setrendimiento(txtRend.getText());
        obj.setrecargo(Double.parseDouble(txtRecargo.getText()));
        obj.setid_contrato(Integer.parseInt(txtID.getText()));
        obj.setcodigo(Integer.parseInt(txtCodigo.getText()));

        ClaseCombo_Contrato mostrar = new ClaseCombo_Contrato();

        int costo = (mostrar.CargarCosto(Valor2));
        int produccion = (mostrar.CargarProduccion(Valor3));
        int cliente = (mostrar.CargarCliente(Valor1));

        obj.setcosto(costo);
        obj.setproduccion(produccion);
        obj.setid_cliente(cliente);
        obj.setid_tipo_contrato(Integer.parseInt(CMB));

        if (obj.modificarContrato()) {
            JOptionPane.showMessageDialog(null, "Datos actualizados con exito");
            cargarContrato();
            LimpiarCampos();
        }else{
            JOptionPane.showMessageDialog(null, "Error al actualizar datos");
        }
         }

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnFiltroProdAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnFiltroProdAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFiltroProdAncestorAdded

    private void btnFiltroProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiltroProdMouseClicked
        FiltroRendimiento FR = new FiltroRendimiento();
        FR.setVisible(true);
    }//GEN-LAST:event_btnFiltroProdMouseClicked

    private void btnFiltroProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFiltroProdActionPerformed

    private void btnFiltroManAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnFiltroManAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFiltroManAncestorAdded

    private void btnFiltroManMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiltroManMouseClicked
        FiltroCosto FiC = new FiltroCosto();
        FiC.setVisible(true);
    }//GEN-LAST:event_btnFiltroManMouseClicked

    private void btnFiltroManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroManActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFiltroManActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        cargarContrato();
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
       LimpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtFechaFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaFinActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaContrato;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnFiltroCli;
    private javax.swing.JButton btnFiltroMan;
    private javax.swing.JButton btnFiltroProd;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JComboBox<ClaseCombo_Contrato> cbxTipoContrato;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JFormattedTextField txtFechaFin;
    private javax.swing.JFormattedTextField txtFechaIn;
    private javax.swing.JTextField txtGarantia;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMensualidad;
    public static javax.swing.JTextField txtProduccion;
    private javax.swing.JTextField txtRecargo;
    private javax.swing.JTextField txtRend;
    public static javax.swing.JFormattedTextField txtTipoMan;
    // End of variables declaration//GEN-END:variables
}
