/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geopanels;

import Clases.ClaseEmpresa;
import Clases.ClaseImagen_Empresa;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author jalex
 */
public class Empresas extends javax.swing.JPanel {

    //Pasando los parametros de la tabla.
    public static ResultSet res;
    //Instanciando la clase para la imagen.
    ClaseImagen_Empresa funciones = new ClaseImagen_Empresa();
    ClaseEmpresa Obj = new ClaseEmpresa();
        
    public Empresas() {
        initComponents();
        txtID.setVisible(false);
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_resultado = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtempresa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtgiro = new javax.swing.JTextField();
        txtrazon = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtpatronal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtrepresentante = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnLogo = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();

        setBackground(new java.awt.Color(42, 51, 56));
        setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(42, 51, 56));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(149, 162, 166));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Empresa.png"))); // NOI18N
        jLabel2.setText("Empresa");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel2.setIconTextGap(20);

        jLabel1.setForeground(new java.awt.Color(21, 179, 89));

        jPanel7.setBackground(new java.awt.Color(42, 51, 56));

        btnAgregar.setBackground(new java.awt.Color(27, 35, 41));
        btnAgregar.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(149, 162, 166));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Añadir.png"))); // NOI18N
        btnAgregar.setText("Añadir Elemento");
        btnAgregar.setBorderPainted(false);
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setOpaque(true);
        btnAgregar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Añadir Hover.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(27, 35, 41));
        btnActualizar.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(149, 162, 166));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Actualizar.png"))); // NOI18N
        btnActualizar.setText("Actualizar Lista");
        btnActualizar.setBorderPainted(false);
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.setOpaque(true);
        btnActualizar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Actualizar Hover.png"))); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        tabla_resultado.setBackground(new java.awt.Color(42, 51, 56));
        tabla_resultado.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        tabla_resultado.setForeground(new java.awt.Color(149, 162, 166));
        tabla_resultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Empresa", "Giro comercial", "Razón social", "Correo", "Logo", "Registro patronal", "Direccion", "Representante"
            }
        ));
        tabla_resultado.setGridColor(new java.awt.Color(50, 54, 59));
        tabla_resultado.setOpaque(false);
        tabla_resultado.setSelectionBackground(new java.awt.Color(149, 162, 166));
        tabla_resultado.setSelectionForeground(new java.awt.Color(50, 54, 59));
        tabla_resultado.getTableHeader().setReorderingAllowed(false);
        tabla_resultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_resultadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_resultado);

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(149, 162, 166));
        jLabel4.setText(" Empresa : ");

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(149, 162, 166));
        jLabel6.setText("Correo : ");

        txtempresa.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        txtempresa.setForeground(new java.awt.Color(50, 54, 59));
        txtempresa.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtempresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtempresaKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(149, 162, 166));
        jLabel8.setText("Razón Social : ");

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(149, 162, 166));
        jLabel9.setText("Giro : ");

        txtgiro.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        txtgiro.setForeground(new java.awt.Color(50, 54, 59));
        txtgiro.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtgiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtgiroKeyTyped(evt);
            }
        });

        txtrazon.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        txtrazon.setForeground(new java.awt.Color(50, 54, 59));
        txtrazon.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtrazon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrazonKeyTyped(evt);
            }
        });

        txtcorreo.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        txtcorreo.setForeground(new java.awt.Color(50, 54, 59));
        txtcorreo.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(149, 162, 166));
        jLabel10.setText("Registro Patronal :");

        txtpatronal.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        txtpatronal.setForeground(new java.awt.Color(50, 54, 59));
        txtpatronal.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtpatronal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpatronalKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(149, 162, 166));
        jLabel7.setText("Dirección : ");

        txtdireccion.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        txtdireccion.setForeground(new java.awt.Color(50, 54, 59));
        txtdireccion.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(149, 162, 166));
        jLabel11.setText("Representante :");

        txtrepresentante.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        txtrepresentante.setForeground(new java.awt.Color(50, 54, 59));
        txtrepresentante.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtrepresentante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrepresentanteKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(149, 162, 166));
        jLabel12.setText("Logo : ");

        btnLogo.setBackground(new java.awt.Color(27, 35, 41));
        btnLogo.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnLogo.setForeground(new java.awt.Color(149, 162, 166));
        btnLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Cambiar.png"))); // NOI18N
        btnLogo.setText("Cambiar");
        btnLogo.setBorderPainted(false);
        btnLogo.setContentAreaFilled(false);
        btnLogo.setOpaque(true);
        btnLogo.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Cambiar Hover.png"))); // NOI18N
        btnLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoMouseClicked(evt);
            }
        });
        btnLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoActionPerformed(evt);
            }
        });

        btnlimpiar.setBackground(new java.awt.Color(42, 51, 56));
        btnlimpiar.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        btnlimpiar.setForeground(new java.awt.Color(149, 162, 166));
        btnlimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Toalla.png"))); // NOI18N
        btnlimpiar.setText("Limpiar");
        btnlimpiar.setToolTipText("Limpiar Campos");
        btnlimpiar.setBorderPainted(false);
        btnlimpiar.setContentAreaFilled(false);
        btnlimpiar.setOpaque(true);
        btnlimpiar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Toalla Hover.png"))); // NOI18N
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        lblImagen.setForeground(new java.awt.Color(255, 255, 255));
        lblImagen.setText("Logo de la empresa");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(btnlimpiar)
                                .addGap(29, 29, 29))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(17, 17, 17))
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(19, 19, 19)
                                        .addComponent(txtrepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtgiro, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(49, 49, 49)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtpatronal, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel4))
                                        .addGap(40, 40, 40)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtrazon, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                            .addComponent(txtempresa))))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtcorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                            .addComponent(txtdireccion))
                                        .addGap(68, 68, 68))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(20, 20, 20)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnlimpiar)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(btnLogo))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtrazon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpatronal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txtrepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtgiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        add(jPanel4, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    //Instanciando metodos.
    protected String path;
    protected String save;
    
    public void llenarTabla()
    {
        DefaultTableModel modelo = (DefaultTableModel) tabla_resultado.getModel();
        modelo.setRowCount(0);
        //Realizando la consulta.
        res = Clases.Conexion.Consulta("select * from Empresa");
        try
        {
            while(res.next())
            {
                //Enviando datos a la tabla.
                Vector valor = new Vector();
                valor.add(res.getInt(1));
                valor.add(res.getString(2));
                valor.add(res.getString(3));
                valor.add(res.getString(4));
                valor.add(res.getString(5));
                valor.add(res.getString(6));
                valor.add(res.getString(7));
                valor.add(res.getString(8));
                valor.add(res.getString(9));
                modelo.addRow(valor);
                tabla_resultado.setModel(modelo);
                
                //Ocultando columnas.
                tabla_resultado.getColumnModel().getColumn(0).setMaxWidth(0);
                tabla_resultado.getColumnModel().getColumn(0).setMinWidth(0);
                tabla_resultado.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
                tabla_resultado.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
                tabla_resultado.getColumnModel().getColumn(3).setMaxWidth(0);
                tabla_resultado.getColumnModel().getColumn(3).setMinWidth(0);
                tabla_resultado.getTableHeader().getColumnModel().getColumn(3).setMaxWidth(0);
                tabla_resultado.getTableHeader().getColumnModel().getColumn(3).setMinWidth(0);
                tabla_resultado.getColumnModel().getColumn(5).setMaxWidth(0);
                tabla_resultado.getColumnModel().getColumn(5).setMinWidth(0);
                tabla_resultado.getTableHeader().getColumnModel().getColumn(5).setMaxWidth(0);
                tabla_resultado.getTableHeader().getColumnModel().getColumn(5).setMinWidth(0);
                tabla_resultado.getColumnModel().getColumn(6).setMaxWidth(0);
                tabla_resultado.getColumnModel().getColumn(6).setMinWidth(0);
                tabla_resultado.getTableHeader().getColumnModel().getColumn(6).setMaxWidth(0);
                tabla_resultado.getTableHeader().getColumnModel().getColumn(6).setMinWidth(0);
            }
        }
        catch(Exception e)
        {
            System.out.println(e.toString());
        }
    }
    
    private void btnLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoActionPerformed
       //Llamando a las funciones.
       path = funciones.Seleccionar_Imagen(lblImagen);
       save = funciones.GuardarImagen(lblImagen);
    }//GEN-LAST:event_btnLogoActionPerformed
            
    private void btnLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoMouseClicked
        // TODO add your handling code here:
        Imagen lg = new Imagen();
        lg.setVisible(true);
    }//GEN-LAST:event_btnLogoMouseClicked

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        //Limpiando campos del formulario. 
        txtempresa.setText("");
        txtgiro.setText("");
        txtrazon.setText("");
        txtcorreo.setText("");
        txtpatronal.setText("");
        txtrepresentante.setText("");
        txtdireccion.setText("");
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
       // Tomando los datos del formulario y pasandoles a los atributos de la clase.

       if (txtempresa.getText().equals("") || txtgiro.getText().equals("") || txtrazon.getText().equals("") || txtcorreo.getText().equals("") || txtpatronal.getText().equals("") || txtdireccion.getText().equals("") || txtrepresentante.getText().equals("")) {
           JOptionPane.showMessageDialog(null, "Debes completar todos los campos necesarios para continuar el proceso con normalidad.", "ADVERTENCIA", JOptionPane.INFORMATION_MESSAGE);
       }else{
       
           // Patrón para validar el email.
	   Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");           
           
           // El email a validar.
           String email = txtcorreo.getText();
           
           Matcher mather = pattern.matcher(email);
           
           if (mather.find() == true) {

                Obj.setNombre_empresa(txtempresa.getText());
                Obj.setGiro_comercial(txtgiro.getText());
                Obj.setRazon_social(txtrazon.getText());
                Obj.setCorreo(txtcorreo.getText());
                Obj.setRegistro_patronal(txtpatronal.getText());
                Obj.setDireccion(txtdireccion.getText());
                Obj.setRepresentante(txtrepresentante.getText());
                Obj.setLogo(save);

                if (Obj.getLogo()!= null) {
                    funciones.CargarLogo(Obj.getLogo(), lblImagen);
                }
                if (Obj.GuardarEmpresa()) 
                {
                    JOptionPane.showMessageDialog(this, "Datos modificados");
                    txtempresa.setText("");
                    txtgiro.setText("");
                    txtrazon.setText("");
                    txtcorreo.setText("");
                    txtpatronal.setText("");
                    txtrepresentante.setText("");
                    txtdireccion.setText("");
                    llenarTabla();
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Error al modificar la información");
                    txtempresa.setText("");
                    txtgiro.setText("");
                    txtrazon.setText("");
                    txtcorreo.setText("");
                    txtpatronal.setText("");
                    txtrepresentante.setText("");
                    txtdireccion.setText("");
                }
                
	    } else {
		JOptionPane.showMessageDialog(null, "El correo ingresado no corresponde a una escritura valida, favor corregirlo", "ADVERTENCIA", JOptionPane.INFORMATION_MESSAGE);
	    }

           
       }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
       // Tomando los datos del formulario y pasandoles a los atributos de la clase.

       if (txtempresa.getText().equals("") || txtgiro.getText().equals("") || txtrazon.getText().equals("") || txtcorreo.getText().equals("") || txtpatronal.getText().equals("") || txtdireccion.getText().equals("") || txtrepresentante.getText().equals("")) {
           JOptionPane.showMessageDialog(null, "Debes completar todos los campos necesarios para continuar el proceso con normalidad.", "ADVERTENCIA", JOptionPane.INFORMATION_MESSAGE);
       }else{
       
           // Patrón para validar el email.
	   Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");           
           
           // El email a validar.
           String email = txtcorreo.getText();
           
           Matcher mather = pattern.matcher(email);
           
           if (mather.find() == true){
           
                Obj.setId_empresa(Integer.parseInt(txtID.getText()));
                Obj.setNombre_empresa(txtempresa.getText());
                Obj.setGiro_comercial(txtgiro.getText());
                Obj.setRazon_social(txtrazon.getText());
                Obj.setCorreo(txtcorreo.getText());
                Obj.setRegistro_patronal(txtpatronal.getText());
                Obj.setDireccion(txtdireccion.getText());
                Obj.setRepresentante(txtrepresentante.getText());
                Obj.setLogo(save);

                if (Obj.getLogo()!= null) {
                    funciones.CargarLogo(Obj.getLogo(), lblImagen);
                }
                if (Obj.ModificarEmpresa()) 
                {
                    JOptionPane.showMessageDialog(this, "Datos modificados");
                    txtempresa.setText("");
                    txtgiro.setText("");
                    txtrazon.setText("");
                    txtcorreo.setText("");
                    txtpatronal.setText("");
                    txtrepresentante.setText("");
                    txtdireccion.setText("");
                    llenarTabla();
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Error al modificar la información");
                    txtempresa.setText("");
                    txtgiro.setText("");
                    txtrazon.setText("");
                    txtcorreo.setText("");
                    txtpatronal.setText("");
                    txtrepresentante.setText("");
                    txtdireccion.setText("");
              }
           }else{
           
               JOptionPane.showMessageDialog(null, "El correo ingresado no corresponde a una escritura valida, favor corregirlo", "ADVERTENCIA", JOptionPane.INFORMATION_MESSAGE);
           }
           

       }       
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void tabla_resultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_resultadoMouseClicked
        //Enviando datos de la tabla a los campos.
        int col = tabla_resultado.getSelectedRow();
        txtID.setText(tabla_resultado.getModel().getValueAt(col, 0).toString());
        txtempresa.setText(tabla_resultado.getModel().getValueAt(col, 1).toString());
        txtgiro.setText(tabla_resultado.getModel().getValueAt(col, 2).toString());
        txtrazon.setText(tabla_resultado.getModel().getValueAt(col, 3).toString());
        txtcorreo.setText(tabla_resultado.getModel().getValueAt(col, 4).toString());
        funciones.CargarLogo(tabla_resultado.getModel().getValueAt(col, 5).toString(), lblImagen);
        txtpatronal.setText(tabla_resultado.getModel().getValueAt(col, 6).toString());
        txtdireccion.setText(tabla_resultado.getModel().getValueAt(col, 7).toString());
        txtrepresentante.setText(tabla_resultado.getModel().getValueAt(col, 8).toString());
    }//GEN-LAST:event_tabla_resultadoMouseClicked

    //VALIDACIONES DE CAMPOS.
    private void txtempresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtempresaKeyTyped
        //Validando que no se agreguen numeros.        
        if (!Character.isLetter(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar()) ) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        } 
    }//GEN-LAST:event_txtempresaKeyTyped

    private void txtrazonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrazonKeyTyped
        //Validando que no se agreguen numeros.        
        if (!Character.isLetter(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar()) ) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        } 
    }//GEN-LAST:event_txtrazonKeyTyped

    private void txtpatronalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpatronalKeyTyped
        // Validando solo numeros incluyendo el "-" para el registro patronal.       
        char car = evt.getKeyChar();
        if((car<'0' || car>'9'))
        if((car!='-'|| Character.isLetter(car)))evt.consume();
    }//GEN-LAST:event_txtpatronalKeyTyped

    private void txtrepresentanteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrepresentanteKeyTyped
        //Validando que no se agreguen numeros.        
        if (!Character.isLetter(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar()) ) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        } 
    }//GEN-LAST:event_txtrepresentanteKeyTyped

    private void txtgiroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgiroKeyTyped
        //Validando que no se agreguen numeros.        
        if (!Character.isLetter(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar()) ) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        } 
    }//GEN-LAST:event_txtgiroKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnLogo;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblImagen;
    private javax.swing.JTable tabla_resultado;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtempresa;
    private javax.swing.JTextField txtgiro;
    private javax.swing.JTextField txtpatronal;
    private javax.swing.JTextField txtrazon;
    private javax.swing.JTextField txtrepresentante;
    // End of variables declaration//GEN-END:variables
}
