/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geopanels;

import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author jalex
 */
public class Empresa extends javax.swing.JPanel {

    /**
     * Creates new form Empresa
     */
    public Empresa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAdmin = new javax.swing.JPanel();
        btnEmpleados = new javax.swing.JButton();
        btnEmpresa = new javax.swing.JButton();
        btnEstablecimeintos = new javax.swing.JButton();
        pnlContenedorAdmin = new javax.swing.JPanel();
        btnDepartamentos = new javax.swing.JButton();
        btnMunicipios = new javax.swing.JButton();
        btnBitácora = new javax.swing.JButton();

        pnlAdmin.setBackground(new java.awt.Color(42, 51, 56));
        pnlAdmin.setForeground(new java.awt.Color(42, 51, 56));

        btnEmpleados.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnEmpleados.setForeground(new java.awt.Color(149, 162, 166));
        btnEmpleados.setText("Empleados");
        btnEmpleados.setToolTipText("Formulario de Empleados");
        btnEmpleados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 162, 166), 1, true));
        btnEmpleados.setContentAreaFilled(false);
        btnEmpleados.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Puntero.png"))); // NOI18N
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });

        btnEmpresa.setBackground(new java.awt.Color(149, 162, 166));
        btnEmpresa.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnEmpresa.setForeground(new java.awt.Color(149, 162, 166));
        btnEmpresa.setText("Empresa");
        btnEmpresa.setToolTipText("Formulario de la Empresa");
        btnEmpresa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 162, 166), 1, true));
        btnEmpresa.setContentAreaFilled(false);
        btnEmpresa.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Puntero.png"))); // NOI18N
        btnEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpresaActionPerformed(evt);
            }
        });

        btnEstablecimeintos.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnEstablecimeintos.setForeground(new java.awt.Color(149, 162, 166));
        btnEstablecimeintos.setText("Establecimientos");
        btnEstablecimeintos.setToolTipText("Formulario de Establecimientos");
        btnEstablecimeintos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 162, 166), 1, true));
        btnEstablecimeintos.setContentAreaFilled(false);
        btnEstablecimeintos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Puntero.png"))); // NOI18N
        btnEstablecimeintos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstablecimeintosActionPerformed(evt);
            }
        });

        pnlContenedorAdmin.setBackground(new java.awt.Color(50, 54, 59));
        pnlContenedorAdmin.setMinimumSize(new java.awt.Dimension(761, 523));
        pnlContenedorAdmin.setOpaque(false);
        pnlContenedorAdmin.setLayout(new java.awt.BorderLayout());

        btnDepartamentos.setBackground(new java.awt.Color(149, 162, 166));
        btnDepartamentos.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnDepartamentos.setForeground(new java.awt.Color(149, 162, 166));
        btnDepartamentos.setText("Departamentos");
        btnDepartamentos.setToolTipText("Registro de Departamentos");
        btnDepartamentos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 162, 166), 1, true));
        btnDepartamentos.setContentAreaFilled(false);
        btnDepartamentos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Puntero.png"))); // NOI18N
        btnDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartamentosActionPerformed(evt);
            }
        });

        btnMunicipios.setBackground(new java.awt.Color(149, 162, 166));
        btnMunicipios.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnMunicipios.setForeground(new java.awt.Color(149, 162, 166));
        btnMunicipios.setText("Municipios");
        btnMunicipios.setToolTipText("Registro de municipios");
        btnMunicipios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 162, 166), 1, true));
        btnMunicipios.setContentAreaFilled(false);
        btnMunicipios.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Puntero.png"))); // NOI18N
        btnMunicipios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMunicipiosActionPerformed(evt);
            }
        });

        btnBitácora.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnBitácora.setForeground(new java.awt.Color(149, 162, 166));
        btnBitácora.setText("Bitácora");
        btnBitácora.setToolTipText("Registro de acciones");
        btnBitácora.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 162, 166), 1, true));
        btnBitácora.setContentAreaFilled(false);
        btnBitácora.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Puntero.png"))); // NOI18N
        btnBitácora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBitácoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdminLayout = new javax.swing.GroupLayout(pnlAdmin);
        pnlAdmin.setLayout(pnlAdminLayout);
        pnlAdminLayout.setHorizontalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminLayout.createSequentialGroup()
                .addContainerGap(263, Short.MAX_VALUE)
                .addComponent(btnEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBitácora, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEstablecimeintos, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMunicipios, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(pnlContenedorAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAdminLayout.setVerticalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstablecimeintos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMunicipios, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBitácora, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContenedorAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        // TODO add your handling code here:
        Empleados emp = new Empleados();
        emp.setLocation(5,5);
        emp.setSize(761, 523);
        pnlContenedorAdmin.removeAll();
        pnlContenedorAdmin.add(emp,BorderLayout.CENTER);
        pnlContenedorAdmin.revalidate();
        pnlContenedorAdmin.repaint();
        btnEmpleados.setOpaque(true);
        btnEmpleados.setBackground(new java.awt.Color(27, 35, 41));
        btnEstablecimeintos.setOpaque(false);
        btnEstablecimeintos.setBackground(new java.awt.Color(149, 162, 166));
        btnEmpresa.setOpaque(false);
        btnEmpresa.setBackground(new java.awt.Color(149, 162, 166));
        btnMunicipios.setOpaque(false);
        btnMunicipios.setBackground(new java.awt.Color(149, 162, 166));
        btnDepartamentos.setOpaque(false);
        btnDepartamentos.setBackground(new java.awt.Color(149, 162, 166));
        btnBitácora.setOpaque(false);
        btnBitácora.setBackground(new java.awt.Color(149, 162, 166));
        /*btnEmpleados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 35, 41), 1, true));
        btnEstablecimeintos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 162, 166), 1, true));
        btnEmpresa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 162, 166), 1, true));*/
        
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpresaActionPerformed
        // TODO add your handling code here:
        Empresas em = new Empresas();
        em.setLocation(5,5);
        em.setSize(761, 523);
        pnlContenedorAdmin.removeAll();
        pnlContenedorAdmin.add(em,BorderLayout.CENTER);
        pnlContenedorAdmin.revalidate();
        pnlContenedorAdmin.repaint();
        btnEmpleados.setOpaque(false);
        btnEmpleados.setBackground(new java.awt.Color(149, 162, 166));
        btnEstablecimeintos.setOpaque(false);
        btnEstablecimeintos.setBackground(new java.awt.Color(149, 162, 166));
        btnEmpresa.setOpaque(true);
        btnEmpresa.setBackground(new java.awt.Color(27, 35, 41));
        btnMunicipios.setOpaque(false);
        btnMunicipios.setBackground(new java.awt.Color(149, 162, 166));
        btnDepartamentos.setOpaque(false);
        btnDepartamentos.setBackground(new java.awt.Color(149, 162, 166));
        btnBitácora.setOpaque(false);
        btnBitácora.setBackground(new java.awt.Color(149, 162, 166));
        /*btnEmpresa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 35, 41), 1, true));
        btnEmpleados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 162, 166), 1, true));
        btnEstablecimeintos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 162, 166), 1, true));*/
    }//GEN-LAST:event_btnEmpresaActionPerformed

    private void btnEstablecimeintosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstablecimeintosActionPerformed
        // TODO add your handling code here:
        Establecimientos est = new Establecimientos();
        est.setLocation(5,5);
        est.setSize(761, 523);
        pnlContenedorAdmin.removeAll();
        pnlContenedorAdmin.add(est,BorderLayout.CENTER);
        pnlContenedorAdmin.revalidate();
        pnlContenedorAdmin.repaint();
        btnEmpleados.setOpaque(false);
        btnEmpleados.setBackground(new java.awt.Color(149, 162, 166));
        btnEstablecimeintos.setOpaque(true);
        btnEstablecimeintos.setBackground(new java.awt.Color(27, 35, 41));
        btnEmpresa.setOpaque(false);
        btnEmpresa.setBackground(new java.awt.Color(149, 162, 166));
        btnMunicipios.setOpaque(false);
        btnMunicipios.setBackground(new java.awt.Color(149, 162, 166));
        btnDepartamentos.setOpaque(false);
        btnDepartamentos.setBackground(new java.awt.Color(149, 162, 166));
        btnBitácora.setOpaque(false);
        btnBitácora.setBackground(new java.awt.Color(149, 162, 166));
        /*btnEstablecimeintos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 35, 41), 1, true));
        btnEmpresa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 162, 166), 1, true));
        btnEmpleados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 162, 166), 1, true));*/
    }//GEN-LAST:event_btnEstablecimeintosActionPerformed

    private void btnDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartamentosActionPerformed
        // TODO add your handling code here:
        Departamentos dep = new Departamentos();
        dep.setLocation(5,5);
        dep.setSize(761, 523);
        pnlContenedorAdmin.removeAll();
        pnlContenedorAdmin.add(dep,BorderLayout.CENTER);
        pnlContenedorAdmin.revalidate();
        pnlContenedorAdmin.repaint();
        btnEmpleados.setOpaque(false);
        btnEmpleados.setBackground(new java.awt.Color(149, 162, 166));
        btnDepartamentos.setOpaque(true);
        btnDepartamentos.setBackground(new java.awt.Color(27, 35, 41));
        btnEstablecimeintos.setOpaque(false);        
        btnEstablecimeintos.setBackground(new java.awt.Color(149, 162, 166));
        btnEmpresa.setOpaque(false);
        btnEmpresa.setBackground(new java.awt.Color(149, 162, 166));
        btnBitácora.setOpaque(false);
        btnBitácora.setBackground(new java.awt.Color(149, 162, 166));
        btnMunicipios.setOpaque(false);
        btnMunicipios.setBackground(new java.awt.Color(149, 162, 166));
    }//GEN-LAST:event_btnDepartamentosActionPerformed

    private void btnMunicipiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMunicipiosActionPerformed
        // TODO add your handling code here:
        Municipios mun = new Municipios();
        mun.setLocation(5,5);
        mun.setSize(761, 523);
        pnlContenedorAdmin.removeAll();
        pnlContenedorAdmin.add(mun,BorderLayout.CENTER);
        pnlContenedorAdmin.revalidate();
        pnlContenedorAdmin.repaint();
        btnEmpleados.setOpaque(false);
        btnEmpleados.setBackground(new java.awt.Color(149, 162, 166));
        btnMunicipios.setOpaque(true);
        btnMunicipios.setBackground(new java.awt.Color(27, 35, 41));
        btnEstablecimeintos.setOpaque(false);        
        btnEstablecimeintos.setBackground(new java.awt.Color(149, 162, 166));
        btnEmpresa.setOpaque(false);
        btnEmpresa.setBackground(new java.awt.Color(149, 162, 166));
        btnBitácora.setOpaque(false);
        btnBitácora.setBackground(new java.awt.Color(149, 162, 166));
        btnDepartamentos.setOpaque(false);
        btnDepartamentos.setBackground(new java.awt.Color(149, 162, 166));
    }//GEN-LAST:event_btnMunicipiosActionPerformed

    private void btnBitácoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBitácoraActionPerformed
        // TODO add your handling code here:
        Bitácora bi = new Bitácora();
        bi.setLocation(5,5);
        bi.setSize(761, 523);
        pnlContenedorAdmin.removeAll();
        pnlContenedorAdmin.add(bi,BorderLayout.CENTER);
        pnlContenedorAdmin.revalidate();
        pnlContenedorAdmin.repaint();
        btnEmpleados.setOpaque(false);
        btnEmpleados.setBackground(new java.awt.Color(149, 162, 166));
        btnBitácora.setOpaque(true);
        btnBitácora.setBackground(new java.awt.Color(27, 35, 41));
        btnEstablecimeintos.setOpaque(false);        
        btnEstablecimeintos.setBackground(new java.awt.Color(149, 162, 166));
        btnEmpresa.setOpaque(false);
        btnEmpresa.setBackground(new java.awt.Color(149, 162, 166));
        btnMunicipios.setOpaque(false);
        btnMunicipios.setBackground(new java.awt.Color(149, 162, 166));
        btnDepartamentos.setOpaque(false);
        btnDepartamentos.setBackground(new java.awt.Color(149, 162, 166));
    }//GEN-LAST:event_btnBitácoraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBitácora;
    private javax.swing.JButton btnDepartamentos;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnEmpresa;
    private javax.swing.JButton btnEstablecimeintos;
    private javax.swing.JButton btnMunicipios;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JPanel pnlContenedorAdmin;
    // End of variables declaration//GEN-END:variables
}
