/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geopanels;
import java.awt.BorderLayout;

/**
 *
 * @author jalex
 */
public class FormPrincipal extends javax.swing.JFrame {


    
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlContenedor = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        PnlFotoUsuario = new javax.swing.JPanel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblTipoEmpleado = new javax.swing.JLabel();
        AjustesUsuario = new javax.swing.JButton();
        lblPerfil = new javax.swing.JLabel();
        BtnCerrarSesión = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnAbrirCompra = new javax.swing.JButton();
        btnAbrirAdmin = new javax.swing.JButton();
        btnAbrirMantenimiento = new javax.swing.JButton();
        btnAbrirClientes = new javax.swing.JButton();
        btnAbrirReportes = new javax.swing.JButton();
        btnAbrirEmpresa = new javax.swing.JButton();
        btnAbrirVenta = new javax.swing.JButton();
        btnCerrar1 = new javax.swing.JButton();
        btnMinimizar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Geo Panels");
        setBackground(new java.awt.Color(50, 54, 59));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1366, 768));

        jPanel1.setBackground(new java.awt.Color(42, 51, 56));
        jPanel1.setPreferredSize(new java.awt.Dimension(1066, 568));

        pnlContenedor.setBackground(new java.awt.Color(42, 51, 56));
        pnlContenedor.setForeground(new java.awt.Color(50, 54, 59));
        pnlContenedor.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(27, 35, 41));
        jPanel3.setPreferredSize(new java.awt.Dimension(259, 470));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnlFotoUsuario.setBackground(new java.awt.Color(27, 35, 41));
        PnlFotoUsuario.setName("foto"); // NOI18N

        lblNombreUsuario.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(149, 162, 166));
        lblNombreUsuario.setText("Nombre de Usuario");

        lblTipoEmpleado.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        lblTipoEmpleado.setForeground(new java.awt.Color(149, 162, 166));
        lblTipoEmpleado.setText("Tipo Empleado");

        AjustesUsuario.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        AjustesUsuario.setForeground(new java.awt.Color(149, 162, 166));
        AjustesUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Ajuste.png"))); // NOI18N
        AjustesUsuario.setToolTipText("Ajustes de Usuario");
        AjustesUsuario.setBorder(null);
        AjustesUsuario.setContentAreaFilled(false);
        AjustesUsuario.setHideActionText(true);
        AjustesUsuario.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Ajuste Hover.png"))); // NOI18N
        AjustesUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjustesUsuarioActionPerformed(evt);
            }
        });

        lblPerfil.setForeground(new java.awt.Color(255, 255, 255));
        lblPerfil.setText("Logo de la empresa");

        javax.swing.GroupLayout PnlFotoUsuarioLayout = new javax.swing.GroupLayout(PnlFotoUsuario);
        PnlFotoUsuario.setLayout(PnlFotoUsuarioLayout);
        PnlFotoUsuarioLayout.setHorizontalGroup(
            PnlFotoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFotoUsuarioLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(lblPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlFotoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreUsuario)
                    .addComponent(lblTipoEmpleado)
                    .addComponent(AjustesUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        PnlFotoUsuarioLayout.setVerticalGroup(
            PnlFotoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlFotoUsuarioLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(PnlFotoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PnlFotoUsuarioLayout.createSequentialGroup()
                        .addComponent(lblNombreUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(lblTipoEmpleado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AjustesUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110))
        );

        jPanel3.add(PnlFotoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        BtnCerrarSesión.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        BtnCerrarSesión.setForeground(new java.awt.Color(149, 162, 166));
        BtnCerrarSesión.setText("Cerrar Sesión");
        BtnCerrarSesión.setToolTipText("Cerrar Sesión Actual");
        BtnCerrarSesión.setBorder(null);
        BtnCerrarSesión.setContentAreaFilled(false);
        BtnCerrarSesión.setHideActionText(true);
        BtnCerrarSesión.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Cerrar Sesion Hover.png"))); // NOI18N
        BtnCerrarSesión.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCerrarSesiónMouseClicked(evt);
            }
        });
        BtnCerrarSesión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarSesiónActionPerformed(evt);
            }
        });
        jPanel3.add(BtnCerrarSesión, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 103, 30));

        jPanel5.setBackground(new java.awt.Color(39, 42, 46));
        jPanel5.setAutoscrolls(true);
        jPanel5.setOpaque(false);

        btnAbrirCompra.setBackground(new java.awt.Color(27, 35, 41));
        btnAbrirCompra.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnAbrirCompra.setForeground(new java.awt.Color(149, 162, 166));
        btnAbrirCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Interfaz Compra.png"))); // NOI18N
        btnAbrirCompra.setText("Compra           ");
        btnAbrirCompra.setActionCommand("Compra");
        btnAbrirCompra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 162, 166), 1, true));
        btnAbrirCompra.setBorderPainted(false);
        btnAbrirCompra.setContentAreaFilled(false);
        btnAbrirCompra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAbrirCompra.setIconTextGap(30);
        btnAbrirCompra.setOpaque(true);
        btnAbrirCompra.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Interfaz Compra Hover.png"))); // NOI18N
        btnAbrirCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirCompraActionPerformed(evt);
            }
        });

        btnAbrirAdmin.setBackground(new java.awt.Color(27, 35, 41));
        btnAbrirAdmin.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnAbrirAdmin.setForeground(new java.awt.Color(149, 162, 166));
        btnAbrirAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Interfaz Admin.png"))); // NOI18N
        btnAbrirAdmin.setText("Administración ");
        btnAbrirAdmin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 162, 166), 1, true));
        btnAbrirAdmin.setBorderPainted(false);
        btnAbrirAdmin.setContentAreaFilled(false);
        btnAbrirAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAbrirAdmin.setIconTextGap(30);
        btnAbrirAdmin.setOpaque(true);
        btnAbrirAdmin.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Interfaz Admin Hover.png"))); // NOI18N
        btnAbrirAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirAdminActionPerformed(evt);
            }
        });

        btnAbrirMantenimiento.setBackground(new java.awt.Color(27, 35, 41));
        btnAbrirMantenimiento.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnAbrirMantenimiento.setForeground(new java.awt.Color(149, 162, 166));
        btnAbrirMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Interfaz Mantenimiento.png"))); // NOI18N
        btnAbrirMantenimiento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 162, 166), 1, true));
        btnAbrirMantenimiento.setBorderPainted(false);
        btnAbrirMantenimiento.setContentAreaFilled(false);
        btnAbrirMantenimiento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAbrirMantenimiento.setIconTextGap(30);
        btnAbrirMantenimiento.setLabel("Mantenimiento");
        btnAbrirMantenimiento.setOpaque(true);
        btnAbrirMantenimiento.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Interfaz Mantenimeinto Hover.png"))); // NOI18N
        btnAbrirMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirMantenimientoActionPerformed(evt);
            }
        });

        btnAbrirClientes.setBackground(new java.awt.Color(27, 35, 41));
        btnAbrirClientes.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnAbrirClientes.setForeground(new java.awt.Color(149, 162, 166));
        btnAbrirClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Interfaz Cliente.png"))); // NOI18N
        btnAbrirClientes.setText("Cliente             ");
        btnAbrirClientes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 162, 166), 1, true));
        btnAbrirClientes.setBorderPainted(false);
        btnAbrirClientes.setContentAreaFilled(false);
        btnAbrirClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAbrirClientes.setIconTextGap(30);
        btnAbrirClientes.setOpaque(true);
        btnAbrirClientes.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Interfaz Cliente Hover.png"))); // NOI18N
        btnAbrirClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirClientesActionPerformed(evt);
            }
        });

        btnAbrirReportes.setBackground(new java.awt.Color(27, 35, 41));
        btnAbrirReportes.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnAbrirReportes.setForeground(new java.awt.Color(149, 162, 166));
        btnAbrirReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Interfaz Reporte.png"))); // NOI18N
        btnAbrirReportes.setText("Reportes           ");
        btnAbrirReportes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 162, 166), 1, true));
        btnAbrirReportes.setBorderPainted(false);
        btnAbrirReportes.setContentAreaFilled(false);
        btnAbrirReportes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAbrirReportes.setIconTextGap(30);
        btnAbrirReportes.setOpaque(true);
        btnAbrirReportes.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Interfaz Reportes Hover.png"))); // NOI18N
        btnAbrirReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirReportesActionPerformed(evt);
            }
        });

        btnAbrirEmpresa.setBackground(new java.awt.Color(27, 35, 41));
        btnAbrirEmpresa.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnAbrirEmpresa.setForeground(new java.awt.Color(149, 162, 166));
        btnAbrirEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Interfaz Empresa.png"))); // NOI18N
        btnAbrirEmpresa.setText("Empresa   ");
        btnAbrirEmpresa.setActionCommand("Productos      ");
        btnAbrirEmpresa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 162, 166), 1, true));
        btnAbrirEmpresa.setBorderPainted(false);
        btnAbrirEmpresa.setContentAreaFilled(false);
        btnAbrirEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAbrirEmpresa.setIconTextGap(30);
        btnAbrirEmpresa.setOpaque(true);
        btnAbrirEmpresa.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Interfaz Empresa Hover.png"))); // NOI18N
        btnAbrirEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirEmpresaActionPerformed(evt);
            }
        });

        btnAbrirVenta.setBackground(new java.awt.Color(27, 35, 41));
        btnAbrirVenta.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnAbrirVenta.setForeground(new java.awt.Color(149, 162, 166));
        btnAbrirVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Interfaz Venta.png"))); // NOI18N
        btnAbrirVenta.setText("Venta              ");
        btnAbrirVenta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 162, 166), 1, true));
        btnAbrirVenta.setBorderPainted(false);
        btnAbrirVenta.setContentAreaFilled(false);
        btnAbrirVenta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAbrirVenta.setIconTextGap(30);
        btnAbrirVenta.setOpaque(true);
        btnAbrirVenta.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Interfaz Venta Hover.png"))); // NOI18N
        btnAbrirVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAbrirEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAbrirCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAbrirAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAbrirMantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAbrirClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAbrirReportes, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(btnAbrirVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAbrirMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAbrirVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAbrirClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAbrirCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAbrirAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAbrirReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAbrirEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 199, -1, -1));

        btnCerrar1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnCerrar1.setForeground(new java.awt.Color(149, 162, 166));
        btnCerrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/icons8-cancelar-17.png"))); // NOI18N
        btnCerrar1.setToolTipText("Cerrar");
        btnCerrar1.setBorder(null);
        btnCerrar1.setContentAreaFilled(false);
        btnCerrar1.setHideActionText(true);
        btnCerrar1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/icons8-cancelar-17 (2).png"))); // NOI18N
        btnCerrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrar1ActionPerformed(evt);
            }
        });

        btnMinimizar2.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnMinimizar2.setForeground(new java.awt.Color(149, 162, 166));
        btnMinimizar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/icons8-menos-17.png"))); // NOI18N
        btnMinimizar2.setToolTipText("Minimizar");
        btnMinimizar2.setBorder(null);
        btnMinimizar2.setContentAreaFilled(false);
        btnMinimizar2.setHideActionText(true);
        btnMinimizar2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/icons8-menos-17 (3).png"))); // NOI18N
        btnMinimizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnMinimizar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCerrar1))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMinimizar2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1078, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   

    
    private void AjustesUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjustesUsuarioActionPerformed
        // TODO add your handling code here:
        MiPerfil pr = new MiPerfil();
        pr.setLocation(5,5);
        pr.setSize(781, 553);
        pnlContenedor.removeAll();
        pnlContenedor.add(pr, BorderLayout.CENTER);
        pnlContenedor.revalidate();
        pnlContenedor.repaint();
    }//GEN-LAST:event_AjustesUsuarioActionPerformed

    private void BtnCerrarSesiónMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCerrarSesiónMouseClicked
        // TODO add your handling code here:
        Login log = new Login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnCerrarSesiónMouseClicked

    private void BtnCerrarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarSesiónActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCerrarSesiónActionPerformed

    private void btnAbrirCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirCompraActionPerformed
        // TODO add your handling code here:
        FormCompra com = new FormCompra();
        com.setLocation(5,5);
        com.setSize(781, 553);
        pnlContenedor.removeAll();
        pnlContenedor.add(com, BorderLayout.CENTER);
        pnlContenedor.revalidate();
        pnlContenedor.repaint();
    }//GEN-LAST:event_btnAbrirCompraActionPerformed

    private void btnAbrirAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirAdminActionPerformed
        // TODO add your handling code here:
        Productos Productos = new Productos();
        Productos.setLocation(5,5);
        Productos.setSize(781, 553);
        pnlContenedor.removeAll();
        pnlContenedor.add(Productos, BorderLayout.CENTER);
        pnlContenedor.revalidate();
        pnlContenedor.repaint();
    }//GEN-LAST:event_btnAbrirAdminActionPerformed

    private void btnAbrirMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirMantenimientoActionPerformed
        // TODO add your handling code here:
        Mantenimiento man = new Mantenimiento();
        man.setLocation(5,5);
        man.setSize(781, 553);
        pnlContenedor.removeAll();
        pnlContenedor.add(man, BorderLayout.CENTER);
        pnlContenedor.revalidate();
        pnlContenedor.repaint();
    }//GEN-LAST:event_btnAbrirMantenimientoActionPerformed

    private void btnAbrirClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirClientesActionPerformed
        // TODO add your handling code here:
        Clientes cl = new Clientes();
        cl.setLocation(5,5);
        cl.setSize(781, 553);
        pnlContenedor.removeAll();
        pnlContenedor.add(cl, BorderLayout.CENTER);
        pnlContenedor.revalidate();
        pnlContenedor.repaint();
    }//GEN-LAST:event_btnAbrirClientesActionPerformed

    private void btnAbrirEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirEmpresaActionPerformed
        // TODO add your handling code here:
        Empresa em = new Empresa();
        em.setLocation(5,5);
        em.setSize(781, 553);
        pnlContenedor.removeAll();
        pnlContenedor.add(em, BorderLayout.CENTER);
        pnlContenedor.revalidate();
        pnlContenedor.repaint();
    }//GEN-LAST:event_btnAbrirEmpresaActionPerformed

    private void btnAbrirVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirVentaActionPerformed
        // TODO add your handling code here:
        Venta venta = new Venta();
        venta.setLocation(5,5);
        venta.setSize(781, 553);
        pnlContenedor.removeAll();
        pnlContenedor.add(venta, BorderLayout.CENTER);
        pnlContenedor.revalidate();
        pnlContenedor.repaint();
    }//GEN-LAST:event_btnAbrirVentaActionPerformed

    private void btnCerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrar1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCerrar1ActionPerformed

    private void btnMinimizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizar2ActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(1);
    }//GEN-LAST:event_btnMinimizar2ActionPerformed

    private void btnAbrirReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirReportesActionPerformed
        Reportes com = new Reportes();
        com.setLocation(5,5);
        com.setSize(781, 553);
        pnlContenedor.removeAll();
        pnlContenedor.add(com, BorderLayout.CENTER);
        pnlContenedor.revalidate();
        pnlContenedor.repaint();
    }//GEN-LAST:event_btnAbrirReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjustesUsuario;
    private javax.swing.JButton BtnCerrarSesión;
    private javax.swing.JPanel PnlFotoUsuario;
    public static javax.swing.JButton btnAbrirAdmin;
    public static javax.swing.JButton btnAbrirClientes;
    public static javax.swing.JButton btnAbrirCompra;
    public static javax.swing.JButton btnAbrirEmpresa;
    public static javax.swing.JButton btnAbrirMantenimiento;
    public static javax.swing.JButton btnAbrirReportes;
    public static javax.swing.JButton btnAbrirVenta;
    private javax.swing.JButton btnCerrar1;
    private javax.swing.JButton btnMinimizar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    public static javax.swing.JLabel lblNombreUsuario;
    public static javax.swing.JLabel lblPerfil;
    public static javax.swing.JLabel lblTipoEmpleado;
    private javax.swing.JPanel pnlContenedor;
    // End of variables declaration//GEN-END:variables
}
