/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geopanels;
import Clases.ClaseLogin;
import geopanels.FormPrincipal;
import Clases.ClaseImagen_Empresa;
import static geopanels.FormPrincipal.*;
import javax.swing.JOptionPane;

/**
 *
 * @author jalex
 */
public class Login extends javax.swing.JFrame {

    ClaseLogin Niveles = new ClaseLogin();
    
    public Login() {
        
        initComponents();
        PrimerUso();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    FormPrincipal menu = new FormPrincipal();
    Recuperaciones Recu = new Recuperaciones();
    PrimerEmpresa pre = new PrimerEmpresa();
    PrimerEstablecimiento esta = new PrimerEstablecimiento();
    PrimerUsuario usu = new PrimerUsuario();
    ClaseImagen_Empresa funciones = new ClaseImagen_Empresa();
    ContraPersonal contraNueva = new ContraPersonal();
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();
        btnInicio = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnRecu = new javax.swing.JButton();
        btnPrimerUso = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();
        btnPrimerUso1 = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnMinimizar = new javax.swing.JButton();

        jMenuItem1.setBackground(new java.awt.Color(27, 35, 41));
        jMenuItem1.setForeground(new java.awt.Color(149, 162, 166));
        jMenuItem1.setText("Configuraciones Iniciales");
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log In");
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(27, 35, 41));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(149, 162, 166));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/icons8-perfil-de-gato-50.png"))); // NOI18N

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(149, 162, 166));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/icons8-credenciales-de-usuario-50.png"))); // NOI18N

        txtClave.setBackground(new java.awt.Color(27, 35, 41));
        txtClave.setForeground(new java.awt.Color(149, 162, 166));
        txtClave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(149, 162, 166)));

        btnInicio.setBackground(new java.awt.Color(27, 35, 41));
        btnInicio.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(149, 162, 166));
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/icons8-privado-2-20.png"))); // NOI18N
        btnInicio.setText("Iniciar Sesión");
        btnInicio.setToolTipText("Log In");
        btnInicio.setBorderPainted(false);
        btnInicio.setContentAreaFilled(false);
        btnInicio.setOpaque(true);
        btnInicio.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/icons8-privado-2-20 (1).png"))); // NOI18N
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioMouseClicked(evt);
            }
        });
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        txtUsuario.setBackground(new java.awt.Color(27, 35, 41));
        txtUsuario.setForeground(new java.awt.Color(149, 162, 166));
        txtUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(149, 162, 166)));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(149, 162, 166));
        jLabel6.setText("Contraseña");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(149, 162, 166));
        jLabel7.setText("Usuario");

        btnRecu.setBackground(new java.awt.Color(27, 35, 41));
        btnRecu.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnRecu.setForeground(new java.awt.Color(149, 162, 166));
        btnRecu.setText("Recuperacion de contraseña");
        btnRecu.setToolTipText("Métodos de Recuperación de Contraseñas");
        btnRecu.setBorderPainted(false);
        btnRecu.setContentAreaFilled(false);
        btnRecu.setOpaque(true);
        btnRecu.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/icons8-estado-inactivo-15.png"))); // NOI18N
        btnRecu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecuMouseClicked(evt);
            }
        });
        btnRecu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuActionPerformed(evt);
            }
        });

        btnPrimerUso.setBackground(new java.awt.Color(27, 35, 41));
        btnPrimerUso.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnPrimerUso.setForeground(new java.awt.Color(149, 162, 166));
        btnPrimerUso.setText("Configuración Inicial");
        btnPrimerUso.setToolTipText("Primer Uso");
        btnPrimerUso.setBorderPainted(false);
        btnPrimerUso.setContentAreaFilled(false);
        btnPrimerUso.setOpaque(true);
        btnPrimerUso.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/icons8-estado-inactivo-15.png"))); // NOI18N
        btnPrimerUso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrimerUsoMouseClicked(evt);
            }
        });
        btnPrimerUso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimerUsoActionPerformed(evt);
            }
        });

        btnVer.setBackground(new java.awt.Color(27, 35, 41));
        btnVer.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnVer.setForeground(new java.awt.Color(149, 162, 166));
        btnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/icons8-0-grados-30.png"))); // NOI18N
        btnVer.setToolTipText("Ver");
        btnVer.setBorderPainted(false);
        btnVer.setContentAreaFilled(false);
        btnVer.setOpaque(true);
        btnVer.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/icons8-360-grados-30.png"))); // NOI18N
        btnVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerMouseClicked(evt);
            }
        });
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        btnPrimerUso1.setBackground(new java.awt.Color(27, 35, 41));
        btnPrimerUso1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnPrimerUso1.setForeground(new java.awt.Color(149, 162, 166));
        btnPrimerUso1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/icons8-menú-2-40.png"))); // NOI18N
        btnPrimerUso1.setToolTipText("Opciones de Inicio");
        btnPrimerUso1.setBorderPainted(false);
        btnPrimerUso1.setContentAreaFilled(false);
        btnPrimerUso1.setOpaque(true);
        btnPrimerUso1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrimerUso1MouseClicked(evt);
            }
        });
        btnPrimerUso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimerUso1ActionPerformed(evt);
            }
        });

        btnCerrar.setBackground(new java.awt.Color(27, 35, 41));
        btnCerrar.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(149, 162, 166));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/icons8-cancelar-17.png"))); // NOI18N
        btnCerrar.setToolTipText("Cerrar");
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setOpaque(true);
        btnCerrar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/icons8-cancelar-17 (2).png"))); // NOI18N
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnMinimizar.setBackground(new java.awt.Color(27, 35, 41));
        btnMinimizar.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnMinimizar.setForeground(new java.awt.Color(149, 162, 166));
        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/icons8-menos-17.png"))); // NOI18N
        btnMinimizar.setToolTipText("Minimizar");
        btnMinimizar.setBorderPainted(false);
        btnMinimizar.setContentAreaFilled(false);
        btnMinimizar.setOpaque(true);
        btnMinimizar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/icons8-menos-17 (3).png"))); // NOI18N
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnPrimerUso, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRecu, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUsuario)
                                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnVer, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPrimerUso1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPrimerUso1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnMinimizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecu)
                    .addComponent(btnPrimerUso)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(1);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnPrimerUso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimerUso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrimerUso1ActionPerformed

    private void btnPrimerUso1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrimerUso1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrimerUso1MouseClicked

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerActionPerformed

    private void btnVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerMouseClicked

    private void btnPrimerUsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimerUsoActionPerformed
        if (Niveles.PrimerUso()==1) {
            esta.setVisible(true);
            this.dispose();
        }
        else if (Niveles.PrimerUso()==2) {
            usu.setVisible(true);
            this.dispose();
        }
        else{
            pre.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnPrimerUsoActionPerformed

    private void btnPrimerUsoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrimerUsoMouseClicked
        // TODO add your handling code here:
        pre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPrimerUsoMouseClicked

    private void btnRecuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuActionPerformed

    }//GEN-LAST:event_btnRecuActionPerformed

    private void btnRecuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecuMouseClicked
        // TODO add your handling code here:
        Recu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRecuMouseClicked

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed

        // Llamo a las clases
        String NombreUsuario = txtUsuario.getText();
        String Contra =  txtClave.getText();

        //La contraseña ingresada se manda al metodo para encriptarla,
        //Y asi comparar la con la contraseña ubicada en la base de datos.
        ClaseLogin verificar = new ClaseLogin();
        String contra = verificar.EncriptarPalabra(Contra);

            if (verificar.Login(NombreUsuario, contra) == 1) {
                if (Niveles.primera == null) {

                Seguridad se = new Seguridad();
                se.setVisible(true);
                se.txtID.setText(String.valueOf(Niveles.ID));
                this.dispose();

                }else{

                    if (Niveles.generica == 0) {
                        //funcion para mostrar el perfil
                        funciones.CargarLogo(Niveles.perfil, lblPerfil);
                        lblNombreUsuario.setText(NombreUsuario);
                        menu.setVisible(true);
                        separacion();
                        this.dispose();
                    }else{

                        //Mostrando formulario para establecer la clave personal.
                        contraNueva.setVisible(true);
                        contraNueva.txtIDContra.setText(String.valueOf(Niveles.ID));
                        this.dispose();
                        System.out.println("Has usado una contra generica");
                    }

                }
            }else{
                JOptionPane.showMessageDialog(null, "Error al ingresar al sistema, favor revisar que ningun campo este vacio o las credenciales ingresadas.", "Error en el ingreso", JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseClicked
        // TODO add your handling code here:
        //        menu.setVisible(true);
        //        this.dispose();
    }//GEN-LAST:event_btnInicioMouseClicked

     public void separacion(){
        //Nivel de Gerente
        if (Niveles.nivel == 1) {
            menu.lblTipoEmpleado.setText("Gerente");
            btnAbrirMantenimiento.setVisible(false);
            btnAbrirVenta.setVisible(false);
            btnAbrirClientes.setVisible(false);
            btnAbrirAdmin.setVisible(false);
            btnAbrirEmpresa.setVisible(false);
            btnAbrirCompra.setLocation(6, 6);
            btnAbrirReportes.setLocation(6, 47);
        //Nivel de Cajero
        }else if (Niveles.nivel == 2) {
            lblTipoEmpleado.setText("Cajero");
            btnAbrirVenta.setVisible(false);
            btnAbrirClientes.setVisible(false);
            btnAbrirAdmin.setVisible(false);
            btnAbrirEmpresa.setVisible(false);
            btnAbrirCompra.setVisible(false);
            btnAbrirReportes.setVisible(false);
            
            //Nivel de administrador
            }else if(Niveles.nivel == 3){
            lblTipoEmpleado.setText("Administrador");
            
        //Nivel de Tecnico
        }else if (Niveles.nivel == 4) {
            lblTipoEmpleado.setText("Tecnico");
            btnAbrirVenta.setVisible(false);
            btnAbrirClientes.setVisible(false);
            btnAbrirAdmin.setVisible(false);
            btnAbrirEmpresa.setVisible(false);
            btnAbrirCompra.setVisible(false);
            btnAbrirReportes.setVisible(false);
        //Nivel de vendedor
        }else if (Niveles.nivel == 5) {
            lblTipoEmpleado.setText("Vendedor");
            btnAbrirMantenimiento.setVisible(false);
            btnAbrirVenta.setLocation(6, 6);
            btnAbrirClientes.setLocation(6, 47);
            btnAbrirAdmin.setVisible(false);
            btnAbrirEmpresa.setVisible(false);
            btnAbrirCompra.setVisible(false);
            btnAbrirReportes.setVisible(false);
        }
    }
     
     public void PrimerUso(){
         if (Niveles.PrimerUso()==3) {
            btnPrimerUso.setVisible(false);
         }
     }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JButton btnPrimerUso;
    private javax.swing.JButton btnPrimerUso1;
    private javax.swing.JButton btnRecu;
    private javax.swing.JButton btnVer;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
