/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geopanels;

import java.awt.BorderLayout;

/**
 *
 * @author jalex
 */
public class Productos extends javax.swing.JPanel {

    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAdmin = new javax.swing.JPanel();
        btnPanel = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnTipo = new javax.swing.JButton();
        btnProveedor = new javax.swing.JButton();
        btnMarca = new javax.swing.JButton();
        btnTipoP = new javax.swing.JButton();
        pnlContenedorAdmin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        pnlAdmin.setBackground(new java.awt.Color(42, 51, 56));
        pnlAdmin.setForeground(new java.awt.Color(50, 54, 59));

        btnPanel.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnPanel.setForeground(new java.awt.Color(149, 162, 166));
        btnPanel.setText("Productos");
        btnPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 162, 166), 1, true));
        btnPanel.setContentAreaFilled(false);
        btnPanel.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Puntero.png"))); // NOI18N
        btnPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelActionPerformed(evt);
            }
        });

        btnInventario.setBackground(new java.awt.Color(149, 162, 166));
        btnInventario.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnInventario.setForeground(new java.awt.Color(149, 162, 166));
        btnInventario.setText("Inventario");
        btnInventario.setToolTipText("");
        btnInventario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 162, 166), 1, true));
        btnInventario.setContentAreaFilled(false);
        btnInventario.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Puntero.png"))); // NOI18N
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });

        btnTipo.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnTipo.setForeground(new java.awt.Color(149, 162, 166));
        btnTipo.setText("Tipos");
        btnTipo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 162, 166), 1, true));
        btnTipo.setContentAreaFilled(false);
        btnTipo.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Puntero.png"))); // NOI18N
        btnTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoActionPerformed(evt);
            }
        });

        btnProveedor.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnProveedor.setForeground(new java.awt.Color(149, 162, 166));
        btnProveedor.setText("Proveedores");
        btnProveedor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 162, 166), 1, true));
        btnProveedor.setContentAreaFilled(false);
        btnProveedor.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Puntero.png"))); // NOI18N
        btnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorActionPerformed(evt);
            }
        });

        btnMarca.setBackground(new java.awt.Color(149, 162, 166));
        btnMarca.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnMarca.setForeground(new java.awt.Color(149, 162, 166));
        btnMarca.setText("Marcas");
        btnMarca.setToolTipText("");
        btnMarca.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 162, 166), 1, true));
        btnMarca.setContentAreaFilled(false);
        btnMarca.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Puntero.png"))); // NOI18N
        btnMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcaActionPerformed(evt);
            }
        });

        btnTipoP.setBackground(new java.awt.Color(149, 162, 166));
        btnTipoP.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnTipoP.setForeground(new java.awt.Color(149, 162, 166));
        btnTipoP.setText("TipoProducto");
        btnTipoP.setToolTipText("");
        btnTipoP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 162, 166), 1, true));
        btnTipoP.setContentAreaFilled(false);
        btnTipoP.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Puntero.png"))); // NOI18N
        btnTipoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoPActionPerformed(evt);
            }
        });

        pnlContenedorAdmin.setBackground(new java.awt.Color(50, 54, 59));
        pnlContenedorAdmin.setMinimumSize(new java.awt.Dimension(761, 523));
        pnlContenedorAdmin.setLayout(new java.awt.BorderLayout(5, 5));

        jLabel1.setBackground(new java.awt.Color(42, 51, 56));
        jLabel1.setForeground(new java.awt.Color(21, 179, 89));
        jLabel1.setOpaque(true);
        pnlContenedorAdmin.add(jLabel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnlAdminLayout = new javax.swing.GroupLayout(pnlAdmin);
        pnlAdmin.setLayout(pnlAdminLayout);
        pnlAdminLayout.setHorizontalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenedorAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTipoP, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlAdminLayout.setVerticalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTipoP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContenedorAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelActionPerformed
        // TODO add your handling code here:
        Producto Solares = new Producto();
        Solares.setLocation(5,5);
        Solares.setSize(761, 523);
        pnlContenedorAdmin.removeAll();
        pnlContenedorAdmin.add(Solares,BorderLayout.CENTER);
        pnlContenedorAdmin.revalidate();
        pnlContenedorAdmin.repaint();
        btnMarca.setOpaque(false);
        btnMarca.setBackground(new java.awt.Color(149, 162, 166));
        btnPanel.setOpaque(true);
        btnPanel.setBackground(new java.awt.Color(27, 35, 41));
        btnInventario.setOpaque(false);        
        btnInventario.setBackground(new java.awt.Color(149, 162, 166));
        btnTipoP.setOpaque(false);
        btnTipoP.setBackground(new java.awt.Color(149, 162, 166));
        btnTipo.setOpaque(false);
        btnTipo.setBackground(new java.awt.Color(149, 162, 166));
        btnProveedor.setOpaque(false);
        btnProveedor.setBackground(new java.awt.Color(149, 162, 166));

    }//GEN-LAST:event_btnPanelActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        // TODO add your handling code here:
        Inventariado En = new Inventariado();
        En.setLocation(5,5);
        En.setSize(761, 523);
        pnlContenedorAdmin.removeAll();
        pnlContenedorAdmin.add(En,BorderLayout.CENTER);
        pnlContenedorAdmin.repaint();
        btnMarca.setOpaque(false);
        btnMarca.setBackground(new java.awt.Color(149, 162, 166));
        btnInventario.setOpaque(true);
        btnInventario.setBackground(new java.awt.Color(27, 35, 41));
        btnPanel.setOpaque(false);        
        btnPanel.setBackground(new java.awt.Color(149, 162, 166));
        btnTipoP.setOpaque(false);
        btnTipoP.setBackground(new java.awt.Color(149, 162, 166));
        btnTipo.setOpaque(false);
        btnTipo.setBackground(new java.awt.Color(149, 162, 166));
        btnProveedor.setOpaque(false);
        btnProveedor.setBackground(new java.awt.Color(149, 162, 166));
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoActionPerformed
        // TODO add your handling code here:
        Tipos Tipo = new Tipos();
        Tipo.setLocation(5,5);
        Tipo.setSize(761, 523);
        pnlContenedorAdmin.removeAll();
        pnlContenedorAdmin.add(Tipo, BorderLayout.CENTER);
        pnlContenedorAdmin.repaint();
        btnMarca.setOpaque(false);
        btnMarca.setBackground(new java.awt.Color(149, 162, 166));
        btnTipo.setOpaque(true);
        btnTipo.setBackground(new java.awt.Color(27, 35, 41));
        btnInventario.setOpaque(false);        
        btnInventario.setBackground(new java.awt.Color(149, 162, 166));
        btnTipoP.setOpaque(false);
        btnTipoP.setBackground(new java.awt.Color(149, 162, 166));
        btnPanel.setOpaque(false);
        btnPanel.setBackground(new java.awt.Color(149, 162, 166));
        btnProveedor.setOpaque(false);
        btnProveedor.setBackground(new java.awt.Color(149, 162, 166));

    }//GEN-LAST:event_btnTipoActionPerformed

    private void btnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorActionPerformed
        // TODO add your handling code here:
        Proveedores Prove = new Proveedores();
        Prove.setLocation(5,5);
        Prove.setSize(761, 523);
        pnlContenedorAdmin.removeAll();
        pnlContenedorAdmin.add(Prove,BorderLayout.CENTER);
        pnlContenedorAdmin.revalidate();
        pnlContenedorAdmin.repaint();
        btnMarca.setOpaque(false);
        btnMarca.setBackground(new java.awt.Color(149, 162, 166));
        btnProveedor.setOpaque(true);
        btnProveedor.setBackground(new java.awt.Color(27, 35, 41));
        btnInventario.setOpaque(false);        
        btnInventario.setBackground(new java.awt.Color(149, 162, 166));
        btnTipoP.setOpaque(false);
        btnTipoP.setBackground(new java.awt.Color(149, 162, 166));
        btnTipo.setOpaque(false);
        btnTipo.setBackground(new java.awt.Color(149, 162, 166));
        btnPanel.setOpaque(false);
        btnPanel.setBackground(new java.awt.Color(149, 162, 166));
    }//GEN-LAST:event_btnProveedorActionPerformed

    private void btnMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcaActionPerformed
        // TODO add your handling code here:
        Marcas Mar = new Marcas();
        Mar.setLocation(5,5);
        Mar.setSize(761, 523);
        pnlContenedorAdmin.removeAll();
        pnlContenedorAdmin.add(Mar,BorderLayout.CENTER);
        pnlContenedorAdmin.revalidate();
        pnlContenedorAdmin.repaint();
        btnPanel.setOpaque(false);
        btnPanel.setBackground(new java.awt.Color(149, 162, 166));
        btnMarca.setOpaque(true);
        btnMarca.setBackground(new java.awt.Color(27, 35, 41));
        btnInventario.setOpaque(false);        
        btnInventario.setBackground(new java.awt.Color(149, 162, 166));
        btnTipoP.setOpaque(false);
        btnTipoP.setBackground(new java.awt.Color(149, 162, 166));
        btnTipo.setOpaque(false);
        btnTipo.setBackground(new java.awt.Color(149, 162, 166));
        btnProveedor.setOpaque(false);
        btnProveedor.setBackground(new java.awt.Color(149, 162, 166));
    }//GEN-LAST:event_btnMarcaActionPerformed

    private void btnTipoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoPActionPerformed
        // TODO add your handling code here:
        TipoProducto tp = new TipoProducto();
        tp.setLocation(5,5);
        tp.setSize(761, 523);
        pnlContenedorAdmin.removeAll();
        pnlContenedorAdmin.add(tp,BorderLayout.CENTER);
        pnlContenedorAdmin.revalidate();
        pnlContenedorAdmin.repaint();
        btnPanel.setOpaque(false);
        btnPanel.setBackground(new java.awt.Color(149, 162, 166));
        btnTipoP.setOpaque(true);
        btnTipoP.setBackground(new java.awt.Color(27, 35, 41));
        btnInventario.setOpaque(false);        
        btnInventario.setBackground(new java.awt.Color(149, 162, 166));
        btnMarca.setOpaque(false);
        btnMarca.setBackground(new java.awt.Color(149, 162, 166));
        btnTipo.setOpaque(false);
        btnTipo.setBackground(new java.awt.Color(149, 162, 166));
        btnProveedor.setOpaque(false);
        btnProveedor.setBackground(new java.awt.Color(149, 162, 166));
    }//GEN-LAST:event_btnTipoPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnMarca;
    private javax.swing.JButton btnPanel;
    private javax.swing.JButton btnProveedor;
    private javax.swing.JButton btnTipo;
    private javax.swing.JButton btnTipoP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JPanel pnlContenedorAdmin;
    // End of variables declaration//GEN-END:variables
}
